'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AD01VEN1
    Public Property FSUCODE As String
    Public Property FSUNAME As String
    Public Property FSUNAMET As String
    Public Property FSHORTNM As String
    Public Property FADD1 As String
    Public Property FADD2 As String
    Public Property FADD3 As String
    Public Property FPROVINCE As String
    Public Property FPROVCD As String
    Public Property FCITYCD As String
    Public Property FTEL As String
    Public Property FTELEX As String
    Public Property FFAX As String
    Public Property FEMAIL As String
    Public Property FMD As String
    Public Property FCONT1 As String
    Public Property FCONT2 As String
    Public Property FCONT3 As String
    Public Property FCTEL1 As String
    Public Property FCTEL2 As String
    Public Property FCTEL3 As String
    Public Property FSTDATE As Nullable(Of Date)
    Public Property FCRTERMTY As String
    Public Property FCRTERM As Nullable(Of Double)
    Public Property FCRLIMIT As Nullable(Of Double)
    Public Property FCATEGORY As String
    Public Property FACCD As String
    Public Property FARACCD As String
    Public Property FRETENTAC As String
    Public Property FAIRLINECD As String
    Public Property FPOSTAL As String
    Public Property FPAIDTO As String
    Public Property FSUTYPE As String
    Public Property FUNQFLAG As String
    Public Property FCURRENCY As String
    Public Property FTAXID As String
    Public Property FPAYTYPE As String
    Public Property FBKCODE As String
    Public Property FBKACNO As String
    Public Property FBKLOCK As String
    Public Property FPWTAX As Nullable(Of Double)
    Public Property FGRPCODE As String
    Public Property FPRETENT As Nullable(Of Double)
    Public Property FNOTUSE As String
    Public Property FENTBY As String
    Public Property FENTDATE As Nullable(Of Date)
    Public Property FUPDBY As String
    Public Property FUPDDATE As Nullable(Of Date)
    Public Property FPICTURE As Byte()
    Public Property FVATYN As String
    Public Property FTRBKCODE As String
    Public Property FTRBKBRNCD As String
    Public Property FCUTYPE As String
    Public Property FCUTYPER As String
    Public Property FVATED As Nullable(Of Byte)
    Public Property FCOMPSOURCE As String
    Public Property FPAYTYPECODE As String
    Public Property SAPVENDOR As String
    Public Property StmDate As Nullable(Of Date)
    Public Property SAPPAYTERM As String
    Public Property FBRANCHCODE As String
    Public Property FBRANCHNAME As String
    Public Property FBRANCHTYPE As Nullable(Of Integer)

End Class
