'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AD13PAY2
    Public Property FTRNNO As String
    Public Property FVOUNO As String
    Public Property FSUREFNO As String
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FCREDITCD As String
    Public Property FACCD As String
    Public Property FITEMNO As String
    Public Property FCOLPRDNO As String
    Public Property FARETENT As Nullable(Of Double)
    Public Property FPRETENT As Nullable(Of Double)
    Public Property FSERIALNO As String
    Public Property FPAYTYPECODE As String

End Class
