'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AD14ADJ1
    Public Property FYEAR As String
    Public Property FVOUCD As String
    Public Property FVOUNO As String
    Public Property FVOUDATE As Nullable(Of Date)
    Public Property FMDATE As Nullable(Of Date)
    Public Property FAPTYPE As String
    Public Property FVOUTYPE As String
    Public Property FSUCODE As String
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FACCD As String
    Public Property FREMARK As String
    Public Property FGLFLAG As String
    Public Property FUPDFLAG As String
    Public Property FCOMPLETE As Nullable(Of Double)
    Public Property FENTDATE As Nullable(Of Date)
    Public Property FPRJCODE As String
    Public Property FDAMT1 As Nullable(Of Double)
    Public Property FDAMT2 As Nullable(Of Double)
    Public Property FDAMT3 As Nullable(Of Double)
    Public Property FDACCD1 As String
    Public Property FDACCD2 As String
    Public Property FDACCD3 As String
    Public Property FDIVCODE As String
    Public Property FNETAR As Nullable(Of Double)

End Class
