'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BD02SMPL
    Public Property FMOLDNO As String
    Public Property FPDCODE As String
    Public Property FSONO As String
    Public Property FCUCODE As String
    Public Property FEXTCUQTY As Nullable(Of Double)
    Public Property FEXTCULOC As String
    Public Property FEXTCUFILE As String
    Public Property FLOCCUQTY As Nullable(Of Double)
    Public Property FLOCCULOC As String
    Public Property FLOCCUFILE As String
    Public Property FEXTQTY As Nullable(Of Double)
    Public Property FEXTLOC As String
    Public Property FEXTFILE As String
    Public Property FDRWQTY As Nullable(Of Double)
    Public Property FDRWNO As String
    Public Property FDRWLOC As String
    Public Property FDRWFILE As String

End Class
