'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BD06PSET
    Public Property FREPRJNO As String
    Public Property FSUCODE As String
    Public Property FSERIALNO As String
    Public Property FPDCODE As String
    Public Property FROUTECODE As String
    Public Property FOPSEQ As String
    Public Property FOPDESC As String
    Public Property FPERCENTED As Double
    Public Property FUSERID As String
    Public Property FDATE As Date

End Class
