'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BD10DIVI
    Public Property FDIVCODE As String
    Public Property FDIVNAME As String
    Public Property FDIVNAMET As String
    Public Property FDIVMG As String
    Public Property FADD1 As String
    Public Property FADD2 As String
    Public Property FADD3 As String
    Public Property FPOSTAL As String
    Public Property FCOMPTAXNO As String
    Public Property FSOCIALNO As String
    Public Property FSCBRANCH As String
    Public Property FPRAC As String
    Public Property FTAXAC As String
    Public Property FSOCIALAC As String
    Public Property FPFAC As String
    Public Property FLOANAC As String
    Public Property FLOANPFAC As String
    Public Property FADVAC As String
    Public Property FOTHAC As String
    Public Property FHOUSEAC As String
    Public Property FBONUSAC As String
    Public Property FBONUSAC2 As String
    Public Property FBONUSAC3 As String
    Public Property FPRNMARK As String
    Public Property FRETFAC As String
    Public Property COMID As String

End Class
