'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BD12SECT
    Public Property FDPCODE As String
    Public Property FSECCODE As String
    Public Property FSECNAME As String
    Public Property FCSCN As String
    Public Property FSECMG As String
    Public Property FSECTYPE As String

End Class
