'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BD22BKLG
    Public Property FCASHTYPE As String
    Public Property FBKCHQ As String
    Public Property FCHQNO As String
    Public Property FCHQDATE As Nullable(Of Date)
    Public Property FCHQAMT As Nullable(Of Double)
    Public Property FBKCODE As String
    Public Property FVOUNO As String
    Public Property FVOUDATE As Nullable(Of Date)
    Public Property FMDATE As Nullable(Of Date)
    Public Property FDUEDATE As Nullable(Of Date)
    Public Property FDESC As String
    Public Property FBKVOUTYPE As String
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FCASHIERCD As String
    Public Property FBKCODE2 As String
    Public Property FBKACNO2 As String
    Public Property FCONTCODE As String
    Public Property FCONTNAME As String
    Public Property FENTDATE As Nullable(Of Date)
    Public Property FPRJCODE As String

End Class
