'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BD25CFA2
    Public Property FYEAR As String
    Public Property FACCD As String
    Public Property FCSCN As String
    Public Property FREPRJNO As String
    Public Property FCFAM0 As Nullable(Of Double)
    Public Property FCFAM1 As Nullable(Of Double)
    Public Property FCFAM2 As Nullable(Of Double)
    Public Property FCFAM3 As Nullable(Of Double)
    Public Property FCFAM4 As Nullable(Of Double)
    Public Property FCFAM5 As Nullable(Of Double)
    Public Property FCFAM6 As Nullable(Of Double)
    Public Property FCFAM7 As Nullable(Of Double)
    Public Property FCFAM8 As Nullable(Of Double)
    Public Property FCFAM9 As Nullable(Of Double)
    Public Property FCFAM10 As Nullable(Of Double)
    Public Property FCFAM11 As Nullable(Of Double)
    Public Property FCFAM12 As Nullable(Of Double)
    Public Property FCFAM13 As Nullable(Of Double)
    Public Property FCFAM14 As Nullable(Of Double)
    Public Property FCFAM15 As Nullable(Of Double)
    Public Property FCFAM1A As Nullable(Of Double)
    Public Property FCFAM2A As Nullable(Of Double)
    Public Property FCFAM3A As Nullable(Of Double)
    Public Property FCFAM4A As Nullable(Of Double)
    Public Property FCFAM5A As Nullable(Of Double)
    Public Property FCFAM6A As Nullable(Of Double)
    Public Property FCFAM7A As Nullable(Of Double)
    Public Property FCFAM8A As Nullable(Of Double)
    Public Property FCFAM9A As Nullable(Of Double)
    Public Property FCFAM10A As Nullable(Of Double)
    Public Property FCFAM11A As Nullable(Of Double)
    Public Property FCFAM12A As Nullable(Of Double)
    Public Property FCFAM13A As Nullable(Of Double)
    Public Property FCFAM14A As Nullable(Of Double)
    Public Property FCFAM15A As Nullable(Of Double)
    Public Property FCFAM1B As Nullable(Of Double)
    Public Property FCFAM2B As Nullable(Of Double)
    Public Property FCFAM3B As Nullable(Of Double)
    Public Property FCFAM4B As Nullable(Of Double)
    Public Property FCFAM5B As Nullable(Of Double)
    Public Property FCFAM6B As Nullable(Of Double)
    Public Property FCFAM7B As Nullable(Of Double)
    Public Property FCFAM8B As Nullable(Of Double)
    Public Property FCFAM9B As Nullable(Of Double)
    Public Property FCFAM10B As Nullable(Of Double)
    Public Property FCFAM11B As Nullable(Of Double)
    Public Property FCFAM12B As Nullable(Of Double)
    Public Property FCFAM13B As Nullable(Of Double)
    Public Property FCFAM14B As Nullable(Of Double)
    Public Property FCFAM15B As Nullable(Of Double)
    Public Property FCFAM1C As Nullable(Of Double)
    Public Property FCFAM2C As Nullable(Of Double)
    Public Property FCFAM3C As Nullable(Of Double)
    Public Property FCFAM4C As Nullable(Of Double)
    Public Property FCFAM5C As Nullable(Of Double)
    Public Property FCFAM6C As Nullable(Of Double)
    Public Property FCFAM7C As Nullable(Of Double)
    Public Property FCFAM8C As Nullable(Of Double)
    Public Property FCFAM9C As Nullable(Of Double)
    Public Property FCFAM10C As Nullable(Of Double)
    Public Property FCFAM11C As Nullable(Of Double)
    Public Property FCFAM12C As Nullable(Of Double)
    Public Property FCFAM13C As Nullable(Of Double)
    Public Property FCFAM14C As Nullable(Of Double)
    Public Property FCFAM15C As Nullable(Of Double)
    Public Property FCFAM1D As Nullable(Of Double)
    Public Property FCFAM2D As Nullable(Of Double)
    Public Property FCFAM3D As Nullable(Of Double)
    Public Property FCFAM4D As Nullable(Of Double)
    Public Property FCFAM5D As Nullable(Of Double)
    Public Property FCFAM6D As Nullable(Of Double)
    Public Property FCFAM7D As Nullable(Of Double)
    Public Property FCFAM8D As Nullable(Of Double)
    Public Property FCFAM9D As Nullable(Of Double)
    Public Property FCFAM10D As Nullable(Of Double)
    Public Property FCFAM11D As Nullable(Of Double)
    Public Property FCFAM12D As Nullable(Of Double)
    Public Property FCFAM13D As Nullable(Of Double)
    Public Property FCFAM14D As Nullable(Of Double)
    Public Property FCFAM15D As Nullable(Of Double)

End Class
