'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CD11PAJ3
    Public Property FPAJNO As String
    Public Property FPDCODE As String
    Public Property FROUTECODE As String
    Public Property FOPSEQ As String
    Public Property FCOMPCODE As String
    Public Property FOLDUPRICE As Nullable(Of Double)
    Public Property FNEWUPRICE As Nullable(Of Double)
    Public Property FQTY As Nullable(Of Double)
    Public Property FCOMPQSCR As Nullable(Of Double)
    Public Property FOLDAMOUNT As Nullable(Of Double)
    Public Property FNEWAMOUNT As Nullable(Of Double)

End Class
