'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CD20CTLG
    Public Property FPDCODE As String
    Public Property FWONO As String
    Public Property FLOTNO As String
    Public Property FREPRJNO As String
    Public Property FREPHASE As String
    Public Property FOPCODE As String
    Public Property FDPCODE As String
    Public Property FSECCODE As String
    Public Property FWCCODE As String
    Public Property FOPSEQ As String
    Public Property FPDLINE As String
    Public Property FCOSTTYPE As String
    Public Property FSACCD As String
    Public Property FSOPCODE As String
    Public Property FSDPCODE As String
    Public Property FSSECCODE As String
    Public Property FSWCCODE As String
    Public Property FSOPSEQ As String
    Public Property FGDCODE As String
    Public Property FMATLCODE As String
    Public Property FQTY As Nullable(Of Double)
    Public Property FRJQTY As Nullable(Of Double)
    Public Property FUC As Nullable(Of Double)
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FOPRUN As Nullable(Of Double)
    Public Property FVOUNO As String
    Public Property FVOUDATE As Nullable(Of Date)
    Public Property FMDATE As Nullable(Of Date)
    Public Property FYEAR As String
    Public Property FMOVECODE As String
    Public Property FSUBTYPE As String
    Public Property FITEMNO As String
    Public Property FENTTYPE As String
    Public Property FGRADE As String
    Public Property FENDPRC As String
    Public Property FPRJCODE As String
    Public Property FUPDBY As String
    Public Property FUPDDATE As Nullable(Of Date)
    Public Property FSONO As String
    Public Property FSOITEMNO As String
    Public Property FREFITEMNO As String
    Public Property FREMARK As String

End Class
