'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CD21MEXA
    Public Property FVOUNO As String
    Public Property FVOUDATE As Nullable(Of Date)
    Public Property FMDATE As Nullable(Of Date)
    Public Property FYEAR As String
    Public Property FMOVECODE As String
    Public Property FCOSTTYPE As String
    Public Property FSACCD As String
    Public Property FOPCODE As String
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FPDLINE As String
    Public Property FDPCODE As String
    Public Property FSECCODE As String
    Public Property FWCCODE As String
    Public Property FREPRJNO As String
    Public Property FREPHASE As String
    Public Property FSERIALNO As String

End Class
