'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CD40CTTY
    Public Property FCOSTTYPE As String
    Public Property FCOSTTYNM As String
    Public Property FRETGLFLAG As String
    Public Property FACCD As String
    Public Property FCSCN As String

End Class
