'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class COMMISSIONCARD
    Public Property FTRNYEAR As String
    Public Property CONTRNO As String
    Public Property REFERENCE As String
    Public Property LID As String
    Public Property CALCMONTH As String
    Public Property SALESCODE As String
    Public Property BOOKDATE As Nullable(Of Date)
    Public Property VADATE As Nullable(Of Date)
    Public Property PREPRJNO As String
    Public Property PSERIALNO As String
    Public Property CUSTCODE As String
    Public Property CUSTNAME As String
    Public Property NETPRICE As Nullable(Of Decimal)
    Public Property SALEPRICE As Nullable(Of Decimal)
    Public Property HEADSALES As String
    Public Property HEADZONE As String
    Public Property CONTRACT_DATE As Nullable(Of Date)
    Public Property COMM_SALES_AMT As Nullable(Of Decimal)
    Public Property COMM_TEAMSALES_AMT As Nullable(Of Decimal)
    Public Property COMM_HEADSALES_AMT As Nullable(Of Decimal)
    Public Property COMM_HEADZONE_AMT As Nullable(Of Decimal)
    Public Property APPROVED_DATE As Nullable(Of Date)
    Public Property COMM_APPROVED_SALES As Nullable(Of Decimal)
    Public Property COMM_APPROVED_TEAMSALES As Nullable(Of Decimal)
    Public Property COMM_APPROVED_HEADSALES As Nullable(Of Decimal)
    Public Property COMM_APPROVED_HEADZONE As Nullable(Of Decimal)
    Public Property TRANSFER_DATE As Nullable(Of Date)
    Public Property COMM_TRANSFER_SALES As Nullable(Of Decimal)
    Public Property COMM_TRANSFER_TEAMSALES As Nullable(Of Decimal)
    Public Property COMM_TRANSFER_HEADSALES As Nullable(Of Decimal)
    Public Property COMM_TRANSFER_HEADZONE As Nullable(Of Decimal)
    Public Property PAYMODE As String
    Public Property FTRNCD As String
    Public Property TRANSACTION_DATE As Nullable(Of Date)

End Class
