'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class COMMISSION
    Public Property FAGRNO As String
    Public Property FTRNCD As String
    Public Property PRJNO As String
    Public Property SERIALNO As String
    Public Property REFNUMBER As String
    Public Property CUSTCODE As String
    Public Property BOOKDATE As Nullable(Of Date)
    Public Property TRANSDATE As Nullable(Of Date)
    Public Property NETSALECONTR As Nullable(Of Decimal)
    Public Property SALEPRICE As Nullable(Of Decimal)
    Public Property NETPRICE As Nullable(Of Decimal)
    Public Property PROMOTION As Nullable(Of Decimal)
    Public Property ACTUALPRICE As Nullable(Of Decimal)
    Public Property SALESCODE As String
    Public Property SALESTEAM As String
    Public Property HEADSALES As String
    Public Property HEADZONE As String
    Public Property FUPDFLAG As String

End Class
