'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class COMMISSION_BALANCE
    Public Property PREPRJNO As String
    Public Property SALESCODE As String
    Public Property CALCMONTH As String
    Public Property TOTALCOMM_CONTRACT As Nullable(Of Decimal)
    Public Property TOTALCOMM_APPROVED As Nullable(Of Decimal)
    Public Property TOTALCOMM_TRANSFER As Nullable(Of Decimal)
    Public Property BALANCE As Nullable(Of Decimal)

End Class
