'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CoreAccessLog
    Public Property ID As Integer
    Public Property ACCESSTIME As String
    Public Property IPADDRESS As String
    Public Property MENUID As Integer
    Public Property FUSERID As String
    Public Property UpdateBy As String
    Public Property UpdateDate As Nullable(Of Date)

End Class
