'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CustomerVisit_Storeporc
    Public Property FRINDX As Integer
    Public Property ROW_NUMBER As Nullable(Of Integer)
    Public Property FCONTCODE As String
    Public Property FCONTTNM As String
    Public Property AddressLine1 As String
    Public Property AddressLine2 As String
    Public Property AddressLine3 As String
    Public Property FREPRJNO As String
    Public Property STMDATE As String

End Class
