'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DE00AROLE1
    Public Property FUSERID As String
    Public Property ProjectList As String
    Public Property IsAdmin As String
    Public Property IsEnabled As String
    Public Property UpDateBy As String
    Public Property UpDateDate As Nullable(Of Date)
    Public Property UpDateTime As String

End Class
