'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DE00GROUP
    Public Property QestGroupID As Integer
    Public Property QestGroupName As String
    Public Property SaveBy As String
    Public Property StmDate As Nullable(Of Date)
    Public Property StmTime As String
    Public Property UpDateBy As String
    Public Property UpDateDate As Nullable(Of Date)
    Public Property UpDateTime As String

End Class
