'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DE01QUES2
    Public Property QestNaireID As String
    Public Property QuestionNo As Integer
    Public Property ChoiceCode As Integer
    Public Property IndexOfQuestionNo As Nullable(Of Integer)
    Public Property InColumn As Nullable(Of Integer)
    Public Property ChoiceScroll As Nullable(Of Double)
    Public Property IsRequireDetail As String
    Public Property IsEnable As String
    Public Property ChoiceAliasName As String
    Public Property Cho As Nullable(Of Integer)

End Class
