'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DE01QUES0
    Public Property QestNaireID As String
    Public Property QestNaireName As String
    Public Property ProposeDetail As String
    Public Property QestGroupID As Nullable(Of Integer)
    Public Property ProjectCode As String
    Public Property IsEnable As String
    Public Property SaveBy As String
    Public Property StmDate As Nullable(Of Date)
    Public Property StmTime As String
    Public Property UpDateBy As String
    Public Property UpDateDate As Nullable(Of Date)
    Public Property UpDateTime As String

End Class
