'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DE02QUSN3
    Public Property VISITNUMBER As String
    Public Property QestNaireID As String
    Public Property ItemNO As Integer
    Public Property CompaireProjectNo As String
    Public Property CompaireProjectName As String
    Public Property IsLike As Integer
    Public Property Remark As String

End Class
