'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DE02QUSN2
    Public Property VISITNUMBER As String
    Public Property QestNaireID As String
    Public Property QuestionNo As Integer
    Public Property ChoiceCode As Integer
    Public Property ChoiceScroll As Nullable(Of Double)
    Public Property IsSelected As String
    Public Property IsRequireText As String
    Public Property RequireText As String

End Class
