'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ED01PRJTYPE
    Public Property FRINDX As Integer
    Public Property FPRJGROUP As String
    Public Property FPRJTYPE As String
    Public Property FPRJTYPENAME As String

End Class
