'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ED01COSTLIST
    Public Property FRINDX As Integer
    Public Property FREPRJNO As String
    Public Property FPHASE As String
    Public Property FZONE As String
    Public Property FBLOCK As String
    Public Property FSERIALNO As String
    Public Property FUNIT As String
    Public Property FPDCODE As String
    Public Property FPDNAME As String
    Public Property WBSC1 As String
    Public Property WBSC2 As String
    Public Property WBSC3 As String
    Public Property WBSC4 As String
    Public Property WBSC5 As String

End Class
