'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ED05CMT2
    Public Property FREPRJNO As String
    Public Property FCHGCONCD As String
    Public Property FITEMNO As String
    Public Property FOPSEQ As String
    Public Property FADLABOUR As Nullable(Of Double)
    Public Property FMATLCODE As String
    Public Property FQTY As Nullable(Of Double)

End Class
