'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ED11COST
    Public Property FRNID As Integer
    Public Property FREPRJNO As String
    Public Property FSERIALNO As String
    Public Property FCOSTPRICE As Nullable(Of Double)
    Public Property FGPPERCENT As Nullable(Of Double)
    Public Property FGPPRICE As Nullable(Of Double)
    Public Property FLOCATEPRICE As Nullable(Of Double)
    Public Property FTARGETPRICE As Nullable(Of Double)
    Public Property FPOVERAREA As Nullable(Of Double)
    Public Property FUSERID As String
    Public Property FLOADDATE As Nullable(Of Date)
    Public Property FUPFLAG As String
    Public Property FUPDATE As Nullable(Of Date)
    Public Property FUPTIME As String

End Class
