'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EMPLOYEE_INFO
    Public Property Code As String
    Public Property Employee2 As String
    Public Property Status As String
    Public Property EmployeeType As String
    Public Property Prefix As String
    Public Property Branch As String
    Public Property TitleEng As String
    Public Property TitleThai As String
    Public Property Name1 As String
    Public Property Name2 As String
    Public Property Lastname1 As String
    Public Property Lastname2 As String
    Public Property Nickname As String
    Public Property ImgFile As Byte()
    Public Property IDCardNo As String
    Public Property IDIssueDate As Nullable(Of Date)
    Public Property IDExpDate As Nullable(Of Date)
    Public Property IDCardLocation As String
    Public Property IDCardProvince As String
    Public Property PlaceOfBirth As String
    Public Property BusWay As String
    Public Property BusStation As String
    Public Property SocialNo As String
    Public Property SocialExpDate As Nullable(Of Date)
    Public Property TaxNo As String
    Public Property PassportID As String
    Public Property PassportExpDate As Nullable(Of Date)
    Public Property Department As String
    Public Property Division As String
    Public Property Sectionn As String
    Public Property Positionn As String
    Public Property PhoneNo As String
    Public Property Extension As String
    Public Property FaxNo As String
    Public Property Email As String
    Public Property Job As String
    Public Property StartDate As Nullable(Of Date)
    Public Property StartYear As Nullable(Of Integer)
    Public Property StartMonth As Nullable(Of Integer)
    Public Property StartDay As Nullable(Of Integer)
    Public Property PositionDate As Nullable(Of Date)
    Public Property PositionYear As Nullable(Of Integer)
    Public Property PositionMonth As Nullable(Of Integer)
    Public Property PositionDay As Nullable(Of Integer)
    Public Property Probation As String
    Public Property ProbationDayMonth As Nullable(Of Integer)
    Public Property ProbationDate As Nullable(Of Integer)
    Public Property BirthDate As Nullable(Of Date)
    Public Property DateOfBirthYear As Nullable(Of Integer)
    Public Property DateOfBirthMonth As Nullable(Of Integer)
    Public Property DateOfBirthDay As Nullable(Of Integer)
    Public Property Sex As String
    Public Property Height As Nullable(Of Integer)
    Public Property Weight As Nullable(Of Integer)
    Public Property TotalChild As Nullable(Of Integer)
    Public Property NoofChild As Nullable(Of Integer)
    Public Property StudyChild As Nullable(Of Integer)
    Public Property TotalRelative As Nullable(Of Integer)
    Public Property BigBrother As Nullable(Of Integer)
    Public Property Brother As Nullable(Of Integer)
    Public Property BigSister As Nullable(Of Integer)
    Public Property Sister As Nullable(Of Integer)
    Public Property TaxPaidBy As Nullable(Of Integer)
    Public Property Marital As String
    Public Property Nationality As String
    Public Property MilitaryStatus As String
    Public Property Religion As String
    Public Property Blood As String
    Public Property Origin As String
    Public Property Hobbies As String
    Public Property Sport As String
    Public Property Specialist As String
    Public Property Diseases As String
    Public Property TRNFlag As String
    Public Property ResignDate As Nullable(Of Date)
    Public Property ResignReason As String
    Public Property Approve As String
    Public Property AnnualDay As Nullable(Of Integer)
    Public Property AnnualHour As Nullable(Of Double)
    Public Property Bank As String
    Public Property AccountNo As String
    Public Property AccountName As String
    Public Property CashPercent As Nullable(Of Double)
    Public Property BankPercent As Nullable(Of Double)
    Public Property CashAmount As Nullable(Of Double)
    Public Property BankAmount As Nullable(Of Double)
    Public Property PFNo As String
    Public Property PFDate As Nullable(Of Date)
    Public Property PFDateEnd As Nullable(Of Date)
    Public Property PFComper As Nullable(Of Integer)
    Public Property PFEmpper As Nullable(Of Integer)
    Public Property PFTotal As Nullable(Of Integer)
    Public Property WorkPlan As String
    Public Property District As String
    Public Property Province As String
    Public Property Type As String
    Public Property LateCode As String
    Public Property OTCode As String
    Public Property SpouseNameEng As String
    Public Property SpouseNameThai As String
    Public Property SpouseIDCard As String
    Public Property SpouseBirthDay As Nullable(Of Integer)
    Public Property SpouseWorkOffice As String
    Public Property SpouseRegisterDate As Nullable(Of Date)
    Public Property COMID As String

End Class
