'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GD00CHRT
    Public Property FACCD As String
    Public Property FENNM As String
    Public Property FTHNM As String
    Public Property FACAT As Nullable(Of Double)
    Public Property FACNT As String
    Public Property FACTT As String
    Public Property FACFOR As String
    Public Property FACCLASS As String
    Public Property FCURRENCY As String
    Public Property FGENCSCN As String
    Public Property FTYPE As String
    Public Property FENTDATE As Nullable(Of Date)
    Public Property FUPDDATE As Nullable(Of Date)
    Public Property FUPDBY As String
    Public Property FCOMPLETE As Nullable(Of Double)
    Public Property FNOTE As String
    Public Property FACTCODE As String
    Public Property FISDIRECTCOST As String

End Class
