'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GD03BUDG
    Public Property FYEAR As String
    Public Property FACCD As String
    Public Property FCSCN As String
    Public Property FREPRJNO As String
    Public Property FBGAM0 As Nullable(Of Double)
    Public Property FBGAM1 As Nullable(Of Double)
    Public Property FBGAM2 As Nullable(Of Double)
    Public Property FBGAM3 As Nullable(Of Double)
    Public Property FBGAM4 As Nullable(Of Double)
    Public Property FBGAM5 As Nullable(Of Double)
    Public Property FBGAM6 As Nullable(Of Double)
    Public Property FBGAM7 As Nullable(Of Double)
    Public Property FBGAM8 As Nullable(Of Double)
    Public Property FBGAM9 As Nullable(Of Double)
    Public Property FBGAM10 As Nullable(Of Double)
    Public Property FBGAM11 As Nullable(Of Double)
    Public Property FBGAM12 As Nullable(Of Double)
    Public Property FBGAM13 As Nullable(Of Double)
    Public Property FBGAM14 As Nullable(Of Double)
    Public Property FBGAM15 As Nullable(Of Double)
    Public Property FLASTUPD As Nullable(Of Date)
    Public Property FUSER As String

End Class
