'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GD21GLSM
    Public Property FYEAR As String
    Public Property FACCD As String
    Public Property FCSCN As String
    Public Property FREPRJNO As String
    Public Property FCFAM0 As Nullable(Of Double)
    Public Property FCFAM1 As Nullable(Of Double)
    Public Property FCFAM2 As Nullable(Of Double)
    Public Property FCFAM3 As Nullable(Of Double)
    Public Property FCFAM4 As Nullable(Of Double)
    Public Property FCFAM5 As Nullable(Of Double)
    Public Property FCFAM6 As Nullable(Of Double)
    Public Property FCFAM7 As Nullable(Of Double)
    Public Property FCFAM8 As Nullable(Of Double)
    Public Property FCFAM9 As Nullable(Of Double)
    Public Property FCFAM10 As Nullable(Of Double)
    Public Property FCFAM11 As Nullable(Of Double)
    Public Property FCFAM12 As Nullable(Of Double)
    Public Property FCFAM13 As Nullable(Of Double)
    Public Property FCFAM14 As Nullable(Of Double)
    Public Property FCFAM15 As Nullable(Of Double)
    Public Property FBFAM As Nullable(Of Double)
    Public Property FDBAM As Nullable(Of Double)
    Public Property FCRAM As Nullable(Of Double)
    Public Property FCFAM As Nullable(Of Double)

End Class
