'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GD44ACPR
    Public Property FYEAR As String
    Public Property FPRFROM1 As Nullable(Of Date)
    Public Property FPRTO1 As Nullable(Of Date)
    Public Property FPRFROM2 As Nullable(Of Date)
    Public Property FPRTO2 As Nullable(Of Date)
    Public Property FPRFROM3 As Nullable(Of Date)
    Public Property FPRTO3 As Nullable(Of Date)
    Public Property FPRFROM4 As Nullable(Of Date)
    Public Property FPRTO4 As Nullable(Of Date)
    Public Property FPRFROM5 As Nullable(Of Date)
    Public Property FPRTO5 As Nullable(Of Date)
    Public Property FPRFROM6 As Nullable(Of Date)
    Public Property FPRTO6 As Nullable(Of Date)
    Public Property FPRFROM7 As Nullable(Of Date)
    Public Property FPRTO7 As Nullable(Of Date)
    Public Property FPRFROM8 As Nullable(Of Date)
    Public Property FPRTO8 As Nullable(Of Date)
    Public Property FPRFROM9 As Nullable(Of Date)
    Public Property FPRTO9 As Nullable(Of Date)
    Public Property FPRFROM10 As Nullable(Of Date)
    Public Property FPRTO10 As Nullable(Of Date)
    Public Property FPRFROM11 As Nullable(Of Date)
    Public Property FPRTO11 As Nullable(Of Date)
    Public Property FPRFROM12 As Nullable(Of Date)
    Public Property FPRTO12 As Nullable(Of Date)
    Public Property FPRFROM13 As Nullable(Of Date)
    Public Property FPRTO13 As Nullable(Of Date)
    Public Property FPRFROM14 As Nullable(Of Date)
    Public Property FPRTO14 As Nullable(Of Date)
    Public Property FPRFROM15 As Nullable(Of Date)
    Public Property FPRTO15 As Nullable(Of Date)
    Public Property FENDYFLAG As String
    Public Property FMAXPRDNO As Nullable(Of Double)
    Public Property FEXRATE1 As Nullable(Of Double)
    Public Property FEXRATE2 As Nullable(Of Double)
    Public Property FEXRATE3 As Nullable(Of Double)
    Public Property FEXRATE4 As Nullable(Of Double)
    Public Property FEXRATE5 As Nullable(Of Double)
    Public Property FEXRATE6 As Nullable(Of Double)
    Public Property FEXRATE7 As Nullable(Of Double)
    Public Property FEXRATE8 As Nullable(Of Double)
    Public Property FEXRATE9 As Nullable(Of Double)
    Public Property FEXRATE10 As Nullable(Of Double)
    Public Property FEXRATE11 As Nullable(Of Double)
    Public Property FEXRATE12 As Nullable(Of Double)
    Public Property FEXRATE13 As Nullable(Of Double)
    Public Property FEXRATE14 As Nullable(Of Double)
    Public Property FEXRATE15 As Nullable(Of Double)
    Public Property FNOWEEK1 As Nullable(Of Double)
    Public Property FNOWEEK2 As Nullable(Of Double)
    Public Property FNOWEEK3 As Nullable(Of Double)
    Public Property FNOWEEK4 As Nullable(Of Double)
    Public Property FNOWEEK5 As Nullable(Of Double)
    Public Property FNOWEEK6 As Nullable(Of Double)
    Public Property FNOWEEK7 As Nullable(Of Double)
    Public Property FNOWEEK8 As Nullable(Of Double)
    Public Property FNOWEEK9 As Nullable(Of Double)
    Public Property FNOWEEK10 As Nullable(Of Double)
    Public Property FNOWEEK11 As Nullable(Of Double)
    Public Property FNOWEEK12 As Nullable(Of Double)
    Public Property FNOWEEK13 As Nullable(Of Double)
    Public Property FNOWEEK14 As Nullable(Of Double)
    Public Property FNOWEEK15 As Nullable(Of Double)

End Class
