'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HD02POSI
    Public Property FPOSITION As String
    Public Property FPOSITDESC As String
    Public Property FPOSITALLW As Nullable(Of Double)
    Public Property FFOODALLW As Nullable(Of Double)
    Public Property FPRNMARK As String

End Class
