'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HD04EVL2
    Public Property FEVCODE As String
    Public Property FEVITNO As String
    Public Property FEVITDS As String
    Public Property FEVITENTTY As String
    Public Property FEVITSCORE As Nullable(Of Double)
    Public Property FEVITCHOICE As String

End Class
