'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ITLAWDOC
    Public Property FREPRJNO As String
    Public Property FLANDPROVINCE As String
    Public Property FD1TITLE As String
    Public Property FADDBOOK As String
    Public Property FBUILDINGNO As String
    Public Property FBUILDINGREGISNO As String
    Public Property FTUMBHON As String
    Public Property FAUMPHUR As String
    Public Property FPROVINCE As String
    Public Property FA1 As String
    Public Property FA2 As String
    Public Property FA3 As String
    Public Property FA4 As String
    Public Property FA5 As String
    Public Property FB1 As String
    Public Property FB2 As String
    Public Property FB3 As String
    Public Property FB4 As String
    Public Property FB5 As String
    Public Property FB6 As String
    Public Property FB7 As String
    Public Property FB8 As String
    Public Property FB9 As String
    Public Property FB10 As String
    Public Property FC1 As String
    Public Property FC2 As String
    Public Property FC3 As String
    Public Property FC4 As String
    Public Property FC5 As String
    Public Property FC6 As String

End Class
