'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class KD02WKCN
    Public Property FWCCODE As String
    Public Property FWCNAME As String
    Public Property FDPCODE As String
    Public Property FSECCODE As String
    Public Property FMACHCODE As String
    Public Property FRFOH As Nullable(Of Double)
    Public Property FRVOH As Nullable(Of Double)
    Public Property FRVOHBASE As String
    Public Property FQSPDHRS As Nullable(Of Double)
    Public Property FREXPPCS As Nullable(Of Double)
    Public Property FRSCPPER As Nullable(Of Double)
    Public Property FREGWORK As Nullable(Of Double)
    Public Property FNOPERSON As Nullable(Of Double)
    Public Property FREPRJLIST As String
    Public Property FWCPE As String
    Public Property FWCSE As String
    Public Property FWCFMS As String
    Public Property FWCFMA As String
    Public Property FWCFMC As String

End Class
