'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class KD02WKPS
    Public Property FWCCODE As String
    Public Property FEMPNO As String
    Public Property FPEMPNO As String
    Public Property FTEAMLEVEL As Nullable(Of Integer)
    Public Property FPOSITION As String

End Class
