'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class KD05MOLD
    Public Property FMOLDNO As String
    Public Property FMOLDNAME As String
    Public Property FMOLDIN As Nullable(Of Date)
    Public Property FMOLDOUT As Nullable(Of Date)
    Public Property FWT As String
    Public Property FRT As String
    Public Property FMOLDSIZE As String
    Public Property FSUCODE As String
    Public Property FMACHCODE As String
    Public Property FCAVQTY As Nullable(Of Double)
    Public Property FCYCLETIME As Nullable(Of Double)
    Public Property FSETQTY As Nullable(Of Double)
    Public Property FREMARK As String
    Public Property FSONO As String
    Public Property FDPRETEST As Nullable(Of Date)
    Public Property FDCONFIRM As Nullable(Of Date)
    Public Property FDSEND As Nullable(Of Date)
    Public Property FDAPPROVE As Nullable(Of Date)
    Public Property FMOLDGRP As String
    Public Property FCUCODE As String
    Public Property FCUCHARGE As Nullable(Of Double)

End Class
