'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class KD05RSCD
    Public Property FRSGROUP As String
    Public Property FRSCODE As String
    Public Property FRSDESC As String
    Public Property FSOLVMETH As String
    Public Property ACTIVE As Nullable(Of Integer)
    Public Property GroupType As String

End Class
