'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LD03CMRG
    Public Property FMDATE As Nullable(Of Date)
    Public Property FVOUNO As String
    Public Property FCUCODE As String
    Public Property FNETAMT As Nullable(Of Double)
    Public Property FTYCODE As String
    Public Property FSMCODE As String
    Public Property FRTCOMM As Nullable(Of Double)
    Public Property FTOTCOMM As Nullable(Of Double)
    Public Property FBFCOMM As Nullable(Of Double)
    Public Property FCURCOMM As Nullable(Of Double)
    Public Property FCOLLDATE As Nullable(Of Date)
    Public Property FCOLLDAY As Nullable(Of Double)
    Public Property FPAIDCOMM As Nullable(Of Double)
    Public Property FCFCOMM As Nullable(Of Double)
    Public Property FACOMM1 As Nullable(Of Double)
    Public Property FACOMM2 As Nullable(Of Double)
    Public Property FACOMM3 As Nullable(Of Double)
    Public Property FACOMM4 As Nullable(Of Double)
    Public Property FREMARK As String
    Public Property FREPRJNO As String

End Class
