'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LD04PRMT
    Public Property FYEAR As String
    Public Property FPRDNO As String
    Public Property FVOUNO As String
    Public Property FDFROM As Nullable(Of Date)
    Public Property FDTO As Nullable(Of Date)
    Public Property FPDCODE As String
    Public Property FTARGETQ As Nullable(Of Double)
    Public Property FPDISC As Nullable(Of Double)
    Public Property FADISC As Nullable(Of Double)
    Public Property FUPRICE As Nullable(Of Double)
    Public Property FUPDFLAG As String
    Public Property FENTBY As String
    Public Property FENTDATE As Nullable(Of Date)
    Public Property FUCOMM As Nullable(Of Double)
    Public Property FUPRICE1 As Nullable(Of Double)
    Public Property FUPRICE2 As Nullable(Of Double)
    Public Property FUCOMM1 As Nullable(Of Double)
    Public Property FUCOMM2 As Nullable(Of Double)
    Public Property FITEMNO As String
    Public Property FPRMNOTE As String
    Public Property FREPRJNO As String
    Public Property FREPHASE As String
    Public Property FREZONE As String
    Public Property FSERIALNO As String
    Public Property FPRMDESC As String

End Class
