'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LD06SLAR
    Public Property FSLAREA As String
    Public Property FDESC As String
    Public Property FSUPCODE As String
    Public Property FTYSLAREA As String

End Class
