'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LD09CISL
    Public Property FISCODE As String
    Public Property FISGDES As String
    Public Property FISDESC As String
    Public Property FISSPEC As String
    Public Property FISSEQ As Nullable(Of Integer)
    Public Property FISGFOR As String
    Public Property FISGUSE As String

End Class
