'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LD20SAL1
    Public Property FYEAR As String
    Public Property FPRDNO As String
    Public Property FMDATE As Nullable(Of Date)
    Public Property FVOUDATE As Nullable(Of Date)
    Public Property FVOUNO As String
    Public Property FVOUTYPE As String
    Public Property FMOVECODE As String
    Public Property FSUBTYPE As String
    Public Property FSONO As String
    Public Property FSOITEMNO As String
    Public Property FREFNO As String
    Public Property FITEMNO1 As String
    Public Property FGDCODE As String
    Public Property FCURRENCY As String
    Public Property FEXRATE As Nullable(Of Double)
    Public Property FPDCODE As String
    Public Property FQTY As Nullable(Of Double)
    Public Property FUP As Nullable(Of Double)
    Public Property FAGSALES As Nullable(Of Double)
    Public Property FPDISC1 As Nullable(Of Double)
    Public Property FADISC1 As Nullable(Of Double)
    Public Property FPDISC2 As Nullable(Of Double)
    Public Property FADISC2 As Nullable(Of Double)
    Public Property FASHIP As Nullable(Of Double)
    Public Property FAINSUR As Nullable(Of Double)
    Public Property FAOTHER1 As Nullable(Of Double)
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FPVAT As Nullable(Of Double)
    Public Property FAVAT As Nullable(Of Double)
    Public Property FAOTHER2 As Nullable(Of Double)
    Public Property FDEPOSIT As Nullable(Of Double)
    Public Property FFOCQTY As Nullable(Of Double)
    Public Property FENTDATE As Nullable(Of Date)
    Public Property FPRJCODE As String
    Public Property FCALCOMM As String
    Public Property FUCOMMNEWP As Nullable(Of Double)
    Public Property FACOMMNEWP As Nullable(Of Double)
    Public Property FAFREIGHT As Nullable(Of Double)
    Public Property FAOTHER3 As Nullable(Of Double)
    Public Property FAOTHER4 As Nullable(Of Double)
    Public Property FAOTHER5 As Nullable(Of Double)

End Class
