'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LD20SAL2
    Public Property FYEAR As String
    Public Property FPRDNO As String
    Public Property FMDATE As Nullable(Of Date)
    Public Property FVOUDATE As Nullable(Of Date)
    Public Property FVOUNO As String
    Public Property FVOUTYPE As String
    Public Property FDOCTYPE As String
    Public Property FMOVECODE As String
    Public Property FREFNO As String
    Public Property FSONO As String
    Public Property FDONO As String
    Public Property FRECEIPTNO As String
    Public Property FCREDITCD As String
    Public Property FCRTERM As Nullable(Of Double)
    Public Property FCRTERMDS As String
    Public Property FDUEDATE As Nullable(Of Date)
    Public Property FDIVCODE As String
    Public Property FTYCODE As String
    Public Property FDPCODE As String
    Public Property FSECCODE As String
    Public Property FSMCODE As String
    Public Property FCUCODE As String
    Public Property FCUDOC As String
    Public Property FDES As String
    Public Property FSHIPBY As String
    Public Property FCURRENCY As String
    Public Property FEXRATE As Nullable(Of Double)
    Public Property FAGSALES As Nullable(Of Double)
    Public Property FPDISC1 As Nullable(Of Double)
    Public Property FPDISC2 As Nullable(Of Double)
    Public Property FADISC1 As Nullable(Of Double)
    Public Property FADISC2 As Nullable(Of Double)
    Public Property FASHIP As Nullable(Of Double)
    Public Property FAINSUR As Nullable(Of Double)
    Public Property FAOTHER1 As Nullable(Of Double)
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FPVAT As Nullable(Of Double)
    Public Property FAVAT As Nullable(Of Double)
    Public Property FAOTHER2 As Nullable(Of Double)
    Public Property FPDEPOSIT As Nullable(Of Double)
    Public Property FDEPOSIT As Nullable(Of Double)
    Public Property FENTDATE As Nullable(Of Date)
    Public Property FUSERID As String
    Public Property FPRJCODE As String
    Public Property FRECTTYPE As String
    Public Property FENTTYPE As String
    Public Property FAGRNO As String
    Public Property FCOLPRDNO As String
    Public Property FAFREIGHT As Nullable(Of Double)

End Class
