'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LD23RFCP
    Public Property FYEAR As String
    Public Property FPDCODE As String
    Public Property FREPRJNO As String
    Public Property FFCMETH As String
    Public Property FCURRENCY As String
    Public Property FQFC1 As Nullable(Of Double)
    Public Property FQFC2 As Nullable(Of Double)
    Public Property FQFC3 As Nullable(Of Double)
    Public Property FQFC4 As Nullable(Of Double)
    Public Property FQFC5 As Nullable(Of Double)
    Public Property FQFC6 As Nullable(Of Double)
    Public Property FQFC7 As Nullable(Of Double)
    Public Property FQFC8 As Nullable(Of Double)
    Public Property FQFC9 As Nullable(Of Double)
    Public Property FQFC10 As Nullable(Of Double)
    Public Property FQFC11 As Nullable(Of Double)
    Public Property FQFC12 As Nullable(Of Double)
    Public Property FPFC1 As Nullable(Of Double)
    Public Property FPFC2 As Nullable(Of Double)
    Public Property FPFC3 As Nullable(Of Double)
    Public Property FPFC4 As Nullable(Of Double)
    Public Property FPFC5 As Nullable(Of Double)
    Public Property FPFC6 As Nullable(Of Double)
    Public Property FPFC7 As Nullable(Of Double)
    Public Property FPFC8 As Nullable(Of Double)
    Public Property FPFC9 As Nullable(Of Double)
    Public Property FPFC10 As Nullable(Of Double)
    Public Property FPFC11 As Nullable(Of Double)
    Public Property FPFC12 As Nullable(Of Double)
    Public Property FAFC1 As Nullable(Of Double)
    Public Property FAFC2 As Nullable(Of Double)
    Public Property FAFC3 As Nullable(Of Double)
    Public Property FAFC4 As Nullable(Of Double)
    Public Property FAFC5 As Nullable(Of Double)
    Public Property FAFC6 As Nullable(Of Double)
    Public Property FAFC7 As Nullable(Of Double)
    Public Property FAFC8 As Nullable(Of Double)
    Public Property FAFC9 As Nullable(Of Double)
    Public Property FAFC10 As Nullable(Of Double)
    Public Property FAFC11 As Nullable(Of Double)
    Public Property FAFC12 As Nullable(Of Double)
    Public Property FMINST1 As Nullable(Of Double)
    Public Property FMINST2 As Nullable(Of Double)
    Public Property FMINST3 As Nullable(Of Double)
    Public Property FMINST4 As Nullable(Of Double)
    Public Property FMINST5 As Nullable(Of Double)
    Public Property FMINST6 As Nullable(Of Double)
    Public Property FMINST7 As Nullable(Of Double)
    Public Property FMINST8 As Nullable(Of Double)
    Public Property FMINST9 As Nullable(Of Double)
    Public Property FMINST10 As Nullable(Of Double)
    Public Property FMINST11 As Nullable(Of Double)
    Public Property FMINST12 As Nullable(Of Double)
    Public Property FPBOOK As Nullable(Of Double)
    Public Property FABOOK As Nullable(Of Double)
    Public Property FPDOWN As Nullable(Of Double)
    Public Property FACONTRACT As Nullable(Of Double)
    Public Property FADOWN As Nullable(Of Double)
    Public Property FAFINAL As Nullable(Of Double)
    Public Property FUPDVER As String
    Public Property FUPDBY As String
    Public Property FUPDDATE As Nullable(Of Date)

End Class
