'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LD43PDOR
    Public Property FREQDATE As Nullable(Of Date)
    Public Property FYEAR As String
    Public Property FDOCCD As String
    Public Property FSONO As String
    Public Property FSOITEMNO As String
    Public Property FPDCODE As String
    Public Property FREQQTY As Nullable(Of Double)
    Public Property FUPDBY As String
    Public Property FUPDDATE As Nullable(Of Date)
    Public Property FUPDFLAG As String
    Public Property FAPPBY As String
    Public Property FCHKBOOK As String
    Public Property FCONTCODE As String
    Public Property FREBLOCK As String
    Public Property FREPRJNO As String
    Public Property FREPHASE As String
    Public Property FREZONE As String
    Public Property FBOMMUL As String
    Public Property FREMARK As String

End Class
