'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MD00SITE
    Public Property FMAXPRJ As Nullable(Of Double)
    Public Property FMAXCOMP As Nullable(Of Double)
    Public Property FEXPDATE1 As Nullable(Of Date)
    Public Property FEXPDATE2 As Nullable(Of Date)
    Public Property FEXPDATE3 As Nullable(Of Date)
    Public Property FEXPDATE4 As Nullable(Of Date)
    Public Property FEXPPRNO As String
    Public Property FSUBGLO As String
    Public Property FYEARCONV As Nullable(Of Double)
    Public Property FSUBPRG As String
    Public Property FCHKSUM As Nullable(Of Double)
    Public Property FVERSION As String
    Public Property FSONO As String
    Public Property FRNID As String

End Class
