'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MD02PRG1
    Public Property FPNAME As String
    Public Property FFUNC As String
    Public Property FFUNCTH As String
    Public Property FPLEVEL As String
    Public Property FGROUP As String
    Public Property FTYPE As String
    Public Property FMENUPLACE As String
    Public Property FHWPLACE As String
    Public Property FPARREC As String
    Public Property FPARRET As String
    Public Property FLOGIC As String
    Public Property FBECAREFUL As String
    Public Property FEDITING As String
    Public Property FREMARK As String
    Public Property FWRTBY As String
    Public Property FHDLBY As String
    Public Property FLACTDATE As Nullable(Of Date)

End Class
