'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MD05USR1BeforChangeDeptcode
    Public Property FUSERID As String
    Public Property FPASSWORD As String
    Public Property FPASSWORDT As String
    Public Property FUSERNAME As String
    Public Property FPLEVEL As String
    Public Property FMTRUST As String
    Public Property FCTRUST As String
    Public Property FLASTUPD As Nullable(Of Date)
    Public Property FGODOWN As String
    Public Property FCASHIER As String
    Public Property FSMCODE As String
    Public Property FDIVCODE As String
    Public Property FDPCODE As String
    Public Property FSECCODE As String
    Public Property FDORI As String
    Public Property FROTATE As String
    Public Property FPRDCATE As String
    Public Property FPRDCLASS As String
    Public Property FCUCATE As String
    Public Property FSUCATE As String
    Public Property FQGRPLIST As String
    Public Property FPRLIMIT As Nullable(Of Double)
    Public Property FPDLINE As String
    Public Property FPRSIGN As String
    Public Property FGETMAIL As String
    Public Property FOPCODE As String
    Public Property FWCCODE As String
    Public Property FREPRJLIST As String
    Public Property FPOSITION As String
    Public Property FPDALEVEL As String

End Class
