'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MD08MDLS
    Public Property FPRJCODE As String
    Public Property FPRJNO As Double
    Public Property FPRJNAME As String
    Public Property FPRJNAMET As String
    Public Property FRPATH As String
    Public Property FMNAME As String
    Public Property FINSTALLYN As String
    Public Property FDPATH As String
    Public Property FSELPRN As String
    Public Property FRELPATH As String
    Public Property FIMAGE As String

End Class
