'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MD09PLV1
    Public Property FPLEVEL As String
    Public Property FCTRUST As String
    Public Property FMTRUST As String
    Public Property FRNID As String

End Class
