'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MD102SMM
    Public Property FPASLOCK As String
    Public Property FPASUNLOCK As String
    Public Property FLOCKYN As String
    Public Property FLOCKBY As String
    Public Property FLOCKDT As Nullable(Of Date)
    Public Property FLOCKTM As String

End Class
