'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MD10PACC
    Public Property FMDATE As Date
    Public Property FUSERID As String
    Public Property FPRJCODE As String
    Public Property FDESC As String
    Public Property FMTIMEIN As String
    Public Property FMTIMEOUT As String
    Public Property FCOMCODE As String
    Public Property FPNAME As String
    Public Property FACTION As String
    Public Property FPKEY As String
    Public Property FPCOUNT As Nullable(Of Double)
    Public Property FRNID As String

End Class
