'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MD101URG
    Public Property FSTATIONNO As Double
    Public Property FUSERID As String
    Public Property FPSTNNO As String
    Public Property FMDATEIN As Nullable(Of Date)
    Public Property FMTIMEIN As Nullable(Of Date)
    Public Property FMDATEOUT As Nullable(Of Date)
    Public Property FMTIMEOUT As String
    Public Property FNETUSER As String
    Public Property FCOMCODE As String
    Public Property FLASTACTDT As Nullable(Of Date)
    Public Property FLASTACTTM As String
    Public Property FNONACTCNT As Nullable(Of Double)
    Public Property FRNID As String

End Class
