'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MP01PURC
    Public Property FREPRJNO As String
    Public Property FSERIALNO As String
    Public Property FCLASS As String
    Public Property FTYCODE As String
    Public Property FTOPR As String
    Public Property FTOPO As String
    Public Property FTORA As String
    Public Property FTOPV As String
    Public Property FSTATUS As String
    Public Property FPRAMT As Double
    Public Property FPOAMT As Nullable(Of Double)
    Public Property FRAAMT As Nullable(Of Double)
    Public Property FPVAMT As Nullable(Of Double)
    Public Property FPRQTY As Nullable(Of Double)
    Public Property FPOQTY As Nullable(Of Double)
    Public Property FRAQTY As Nullable(Of Double)
    Public Property FLSTPRDATE As Nullable(Of Date)
    Public Property FLSTPODATE As Nullable(Of Date)
    Public Property FLSTRADATE As Nullable(Of Date)
    Public Property FLSTPVDATE As Nullable(Of Date)
    Public Property FLINKCTL As String

End Class
