'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MP01CONS
    Public Property FREPRJNO As String
    Public Property FSERIALNO As String
    Public Property FSUCODE As String
    Public Property FJONO As String
    Public Property FOPCODE As String
    Public Property FSUMFOP As String
    Public Property FLASTFOP As String
    Public Property FPERCENT As Nullable(Of Integer)
    Public Property FTOTAMT As Nullable(Of Double)
    Public Property FRETENTAMT As Nullable(Of Double)

End Class
