'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ND03HDCT
    Public Property FYEAR As String
    Public Property FPRDNO As String
    Public Property FDIVCODE As String
    Public Property FDPCODE As String
    Public Property FSECCODE As String
    Public Property FOPCODE As String
    Public Property FCSCN As String
    Public Property FEMPLEVEL As String
    Public Property FNOPERSON As Nullable(Of Double)
    Public Property FDIRECT As Nullable(Of Double)
    Public Property FINDIRECT As Nullable(Of Double)
    Public Property FSNE As Nullable(Of Double)
    Public Property FEXEMPT As Nullable(Of Double)
    Public Property FENTTYPE As String
    Public Property FAOPOTR As Nullable(Of Double)
    Public Property FAOPPFR As Nullable(Of Double)

End Class
