'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ND21IBUD
    Public Property FYEAR As String
    Public Property FACCD As String
    Public Property FCSCN As String
    Public Property FSUCODE As String
    Public Property FPLANNO As String
    Public Property FBGAM1 As Nullable(Of Double)
    Public Property FBGAM2 As Nullable(Of Double)
    Public Property FBGAM3 As Nullable(Of Double)
    Public Property FBGAM4 As Nullable(Of Double)
    Public Property FBGAM5 As Nullable(Of Double)
    Public Property FBGAM6 As Nullable(Of Double)
    Public Property FBGAM7 As Nullable(Of Double)
    Public Property FBGAM8 As Nullable(Of Double)
    Public Property FBGAM9 As Nullable(Of Double)
    Public Property FBGAM10 As Nullable(Of Double)
    Public Property FBGAM11 As Nullable(Of Double)
    Public Property FBGAM12 As Nullable(Of Double)
    Public Property FBGAM13 As Nullable(Of Double)
    Public Property FBGAM14 As Nullable(Of Double)
    Public Property FBGAM15 As Nullable(Of Double)
    Public Property FUPDDATE As Nullable(Of Date)
    Public Property FUSER As String
    Public Property FBGTYPE As String
    Public Property FENTTYPE As String
    Public Property FDIVCODE As String
    Public Property FDPCODE As String
    Public Property FSECCODE As String
    Public Property FPDLINE As String
    Public Property FREPRJNO As String
    Public Property FCURRENCY As String
    Public Property FVARYMETH As String
    Public Property FVARYY As String
    Public Property FVARYZ As String
    Public Property FGMETH As String
    Public Property FGRATE As Nullable(Of Double)
    Public Property FBGRT1 As Nullable(Of Double)
    Public Property FBGRT2 As Nullable(Of Double)
    Public Property FBGRT3 As Nullable(Of Double)
    Public Property FBGRT4 As Nullable(Of Double)
    Public Property FBGRT5 As Nullable(Of Double)
    Public Property FBGRT6 As Nullable(Of Double)
    Public Property FBGRT7 As Nullable(Of Double)
    Public Property FBGRT8 As Nullable(Of Double)
    Public Property FBGRT9 As Nullable(Of Double)
    Public Property FBGRT10 As Nullable(Of Double)
    Public Property FBGRT11 As Nullable(Of Double)
    Public Property FBGRT12 As Nullable(Of Double)
    Public Property FBGRT13 As Nullable(Of Double)
    Public Property FBGRT14 As Nullable(Of Double)
    Public Property FBGRT15 As Nullable(Of Double)

End Class
