'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OD10QUO2
    Public Property FQUONO As String
    Public Property FITEMNO As String
    Public Property FPDCODE As String
    Public Property FDESC As String
    Public Property FQTY As Nullable(Of Double)
    Public Property FFOC As Nullable(Of Double)
    Public Property FUP As Nullable(Of Double)
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FSPECTYPE As String
    Public Property FTYPE As String
    Public Property FUMCODE As String
    Public Property FENTQTY As Nullable(Of Double)
    Public Property FENTFOC As Nullable(Of Double)
    Public Property FENTUP As Nullable(Of Double)
    Public Property FENTAMOUNT As Nullable(Of Double)
    Public Property FORDDISC1 As Nullable(Of Double)
    Public Property FORDDISC2 As Nullable(Of Double)
    Public Property FORDDISC3 As Nullable(Of Double)

End Class
