'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OD12ORD1
    Public Property FTRNYEAR As String
    Public Property FTRNNO As String
    Public Property FYEAR As String
    Public Property FORDERNO As String
    Public Property FSODATE As Nullable(Of Date)
    Public Property FMDATE As Nullable(Of Date)
    Public Property FGDCODE As String
    Public Property FCUCODE As String
    Public Property FSMCODE As String
    Public Property FCUDOC As String
    Public Property FDDATE As Nullable(Of Date)
    Public Property FDIVCODE As String
    Public Property FDPCODE As String
    Public Property FSECCODE As String
    Public Property FCOM1 As String
    Public Property FCOM2 As String
    Public Property FNOT1 As String
    Public Property FNOT2 As String
    Public Property FNOT3 As String
    Public Property FSHIPBY As String
    Public Property FPTERM As Nullable(Of Double)
    Public Property FCPTERM As String
    Public Property FPTERMDS As String
    Public Property FTYPRICE As String
    Public Property FENTAMOUNT As Nullable(Of Double)
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FORDDISC As Nullable(Of Double)
    Public Property FORDAMT As Nullable(Of Double)
    Public Property FCASHDISC As Nullable(Of Double)
    Public Property FCASHAMT As Nullable(Of Double)
    Public Property FSHIPPING As Nullable(Of Double)
    Public Property FINSURANCE As Nullable(Of Double)
    Public Property FPVAT As Nullable(Of Double)
    Public Property FAVAT As Nullable(Of Double)
    Public Property FPDEPOSIT As Nullable(Of Double)
    Public Property FDEPOSIT As Nullable(Of Double)
    Public Property FSTATUS As String
    Public Property FENTDATE As Nullable(Of Date)
    Public Property FENTBY As String
    Public Property FUPDDATE As Nullable(Of Date)
    Public Property FUPDBY As String
    Public Property FBATCHNO As String
    Public Property FPRJCODE As String
    Public Property FUPDFLAG As String
    Public Property FCOMPLETE As Nullable(Of Double)
    Public Property FSUCODE As String
    Public Property FSUREFNO As String
    Public Property FCARNO As String
    Public Property FNOINV As Nullable(Of Double)
    Public Property FCURRENCY As String
    Public Property FEXRATE As Nullable(Of Double)
    Public Property FQUONO As String
    Public Property FINCVAT As String
    Public Property FOPCODE As String
    Public Property FPEXP1 As Nullable(Of Double)
    Public Property FCON1 As String
    Public Property FCON2 As String
    Public Property FCON3 As String
    Public Property FDIVDPN As String
    Public Property FQUOTANO As String

End Class
