'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OD14CRN2
    Public Property FVOUNO As String
    Public Property FTRNNO As String
    Public Property FPDCODE As String
    Public Property FDESC As String
    Public Property FQTY As Nullable(Of Double)
    Public Property FDAMGQTY As Nullable(Of Double)
    Public Property FUP As Nullable(Of Double)
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FBINLOC As String
    Public Property FSERIALNO As String
    Public Property FENTQTY As Nullable(Of Double)
    Public Property FENTQDAMG As Nullable(Of Double)
    Public Property FUMCODE As String
    Public Property FENTUP As Nullable(Of Double)
    Public Property FENTAMOUNT As Nullable(Of Double)
    Public Property FORDDISC1 As Nullable(Of Double)
    Public Property FORDDISC2 As Nullable(Of Double)
    Public Property FORDDISC3 As Nullable(Of Double)
    Public Property FITEMNO As String
    Public Property FAVAT As Nullable(Of Double)
    Public Property FREFNO As String
    Public Property FINVITEMNO As String
    Public Property FSUPDCODE As String
    Public Property FFOC As Nullable(Of Double)
    Public Property FENTFOC As Nullable(Of Double)
    Public Property FINVNO As String
    Public Property FINVQTY As Nullable(Of Double)
    Public Property FINVUP As Nullable(Of Double)

End Class
