'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OD15CSH1
    Public Property FTRNYEAR As String
    Public Property FTRNNO As String
    Public Property FYEAR As String
    Public Property FVOUNO As String
    Public Property FVOUDATE As Nullable(Of Date)
    Public Property FMDATE As Nullable(Of Date)
    Public Property FMTIME As String
    Public Property FGDCODE As String
    Public Property FCUCODE As String
    Public Property FSMCODE As String
    Public Property FDIVCODE As String
    Public Property FDPCODE As String
    Public Property FSECCODE As String
    Public Property FCASHRGNO As String
    Public Property FNOT1 As String
    Public Property FNOT2 As String
    Public Property FNOT3 As String
    Public Property FPROMNO As String
    Public Property FCASHIERCD As String
    Public Property FINCVAT As String
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FENTAMOUNT As Nullable(Of Double)
    Public Property FORDDISC As Nullable(Of Double)
    Public Property FORDAMT As Nullable(Of Double)
    Public Property FMEMBERCD As String
    Public Property FCASHDISC As Nullable(Of Double)
    Public Property FCASHAMT As Nullable(Of Double)
    Public Property FPVAT As Nullable(Of Double)
    Public Property FAVAT As Nullable(Of Double)
    Public Property FCNETAMT As String
    Public Property FVOIDNO As String
    Public Property FVOIDDATE As Nullable(Of Date)
    Public Property FDOCSTATUS As String
    Public Property FENTDATE As Nullable(Of Date)
    Public Property FPRJCODE As String
    Public Property FUPDFLAG As String
    Public Property FCOMPLETE As Nullable(Of Double)
    Public Property FCASHTYPE As String
    Public Property FBKCHQ As String
    Public Property FCHQNO As String
    Public Property FBKCHQBR As String
    Public Property FBKCHARGE As Nullable(Of Double)
    Public Property FCHQAMT As Nullable(Of Double)
    Public Property FCHCHANGE As Nullable(Of Double)

End Class
