'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OD15CSH2
    Public Property FVOUNO As String
    Public Property FTRNNO As String
    Public Property FPDCODE As String
    Public Property FQTY As Nullable(Of Double)
    Public Property FFOC As Nullable(Of Double)
    Public Property FUP As Nullable(Of Double)
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FENTUP As Nullable(Of Double)
    Public Property FENTAMOUNT As Nullable(Of Double)
    Public Property FORDDISC1 As Nullable(Of Double)
    Public Property FORDAMT1 As Nullable(Of Double)
    Public Property FVATYN As String
    Public Property FITEMTYPE As String
    Public Property FITEMNO As String

End Class
