'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OD16DBN1
    Public Property FTRNYEAR As String
    Public Property FTRNNO As String
    Public Property FYEAR As String
    Public Property FVOUNO As String
    Public Property FVOUDATE As Nullable(Of Date)
    Public Property FMDATE As Nullable(Of Date)
    Public Property FGDCODE As String
    Public Property FDONO As String
    Public Property FREFNO As String
    Public Property FREFAMT As Nullable(Of Double)
    Public Property FORDERNO As String
    Public Property FSMCODE As String
    Public Property FDIVCODE As String
    Public Property FDPCODE As String
    Public Property FSECCODE As String
    Public Property FCUCODE As String
    Public Property FPTERM As Nullable(Of Double)
    Public Property FCPTERM As String
    Public Property FDUEDATE As Nullable(Of Date)
    Public Property FCURRENCY As String
    Public Property FEXRATE As Nullable(Of Double)
    Public Property FENTAMOUNT As Nullable(Of Double)
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FORDDISC As Nullable(Of Double)
    Public Property FORDAMT As Nullable(Of Double)
    Public Property FCASHDISC As Nullable(Of Double)
    Public Property FCASHAMT As Nullable(Of Double)
    Public Property FPVAT As Nullable(Of Double)
    Public Property FAVAT As Nullable(Of Double)
    Public Property FCOM1 As String
    Public Property FCOM2 As String
    Public Property FSTATUS As String
    Public Property FENTDATE As Nullable(Of Date)
    Public Property FBATCHNO As String
    Public Property FPRJCODE As String
    Public Property FUPDFLAG As String
    Public Property FCOMPLETE As Nullable(Of Double)
    Public Property FCNETAMT As String
    Public Property FINCVAT As String
    Public Property FDNTYPE As String
    Public Property FINVAMT As Nullable(Of Double)

End Class
