'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OD20DLPN
    Public Property FPLANDATE As Date
    Public Property FSONO As String
    Public Property FPDCODE As String
    Public Property FITEMNO As String
    Public Property FBKGQTY As Nullable(Of Double)
    Public Property FFINQTY As Nullable(Of Double)
    Public Property FPNFNDATE As Nullable(Of Date)
    Public Property FPNFNQTY As Nullable(Of Double)
    Public Property FPNDLNO As String
    Public Property FPNDLITEM As String
    Public Property FPNDLDATE As Date
    Public Property FPNDLQTY As Nullable(Of Double)
    Public Property FSHIPNO As String
    Public Property FINVTRNNO As String
    Public Property FPICKFLAG As String

End Class
