'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OD21BODS
    Public Property FVOUNO As String
    Public Property FPDCODE As String
    Public Property FITEMNO1 As String
    Public Property FITEMNO2 As String
    Public Property FDESCTY As String
    Public Property FCREDITCD As String
    Public Property FCOLPRDNO As String
    Public Property FPPMT As Nullable(Of Double)
    Public Property FAPMT As Nullable(Of Double)
    Public Property FDESC As String
    Public Property FTRNNO As String
    Public Property FMEMO1 As String
    Public Property FTCTN As Nullable(Of Double)
    Public Property FTWEIGHT As Nullable(Of Double)
    Public Property FGWEIGHT As Nullable(Of Double)
    Public Property FCTN1 As Nullable(Of Double)
    Public Property FCTN2 As Nullable(Of Double)
    Public Property FCTN3 As Nullable(Of Double)
    Public Property FCTN4 As Nullable(Of Double)
    Public Property FOCTNCD1 As String
    Public Property FOCTNCD2 As String
    Public Property FOCTNCD3 As String
    Public Property FOCTNCD4 As String
    Public Property FCOMPLETE As Nullable(Of Double)

End Class
