'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OD212AGL
    Public Property FAGRNO As String
    Public Property FCOLPRDNO As String
    Public Property FCOLPRDNO2 As String
    Public Property FTYLETTER As String
    Public Property FMDATE As Nullable(Of Date)
    Public Property FDOCSTATUS As String
    Public Property FLETTERNO As String
    Public Property FYEAR As String
    Public Property FENTBY As String
    Public Property FVOIDBY As String
    Public Property FVOIDDATE As Nullable(Of Date)
    Public Property FEXPDATE As Nullable(Of Date)
    Public Property FDEPNAME As String

End Class
