'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OD21LAPM
    Public Property FTRNNO As String
    Public Property FAGRNO As String
    Public Property FITEMNO As Integer
    Public Property FPROMOCODE As String
    Public Property FUPDDATE As Nullable(Of Date)
    Public Property FUPDATEBY As String
    Public Property FMDL As String
    Public Property FACTION As String

End Class
