'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OD21PMUTL
    Public Property FTBLID As Integer
    Public Property FREPRJNO As String
    Public Property FSERIALNO As String
    Public Property FDATE As Nullable(Of Date)
    Public Property FREFNO As String
    Public Property FUSERID As String
    Public Property FTYPE As Nullable(Of Integer)
    Public Property FSTATUS As String

End Class
