'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OD22CLSH
    Public Property FAGRNO As String
    Public Property FCOLPRDNO As String
    Public Property FDUEDATE As Nullable(Of Date)
    Public Property FARENTAL As Nullable(Of Double)
    Public Property FVRENTAL As Nullable(Of Double)
    Public Property FALOAN As Nullable(Of Double)
    Public Property FAINT As Nullable(Of Double)
    Public Property FAINC As Nullable(Of Double)
    Public Property FPDISC As Nullable(Of Double)
    Public Property FADISC As Nullable(Of Double)
    Public Property FMNRFTOT As Nullable(Of Double)
    Public Property FMNRFLOAN As Nullable(Of Double)
    Public Property FMNRFINT As Nullable(Of Double)
    Public Property FRECARENT As Nullable(Of Double)
    Public Property FRECVRENT As Nullable(Of Double)

End Class
