'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OD22PKL1
    Public Property FSONO As String
    Public Property FITEMNO1 As String
    Public Property FCTNQTY As Nullable(Of Double)
    Public Property FCTNNO As Integer
    Public Property FROWNO As Nullable(Of Integer)
    Public Property FCOLNO As Nullable(Of Integer)
    Public Property FCTNTYPE As String
    Public Property FCTNCODE As String
    Public Property FWEIGHT As Nullable(Of Double)
    Public Property FTWEIGHT As Nullable(Of Double)
    Public Property FTCTN As Nullable(Of Integer)
    Public Property FINVNO As String
    Public Property FSHIPNO As String

End Class
