'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OD23SHMT
    Public Property FSHIPNO As String
    Public Property FSHIPDATE As Nullable(Of Date)
    Public Property FSHIPVIA As String
    Public Property FSHIPBY As String
    Public Property FVEHICLENM As String
    Public Property FVEHICLENO As String
    Public Property FTASHIP As Nullable(Of Double)
    Public Property FSHIPROUTE As String
    Public Property FSHIPSTATUS As String

End Class
