'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OD50RLABEL
    Public Property FCONTCODE As String
    Public Property IsLabel As String
    Public Property Saveby As String
    Public Property SaveDate As Nullable(Of Date)

End Class
