'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OD50CIAC
    Public Property FCONTCODE As String
    Public Property FENTBY As String
    Public Property FACTRESULT As String
    Public Property FIACODE As String
    Public Property FACTREMARK As String
    Public Property FACTDATE As Date
    Public Property SEQ As Integer

End Class
