'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PD20WOI2
    Public Property FWONO As String
    Public Property FMDATE As Nullable(Of Date)
    Public Property FWOSTATUS As String
    Public Property FLOTNO As String
    Public Property FOPSEQ As String
    Public Property FWCCODE As String
    Public Property FJONO As String
    Public Property FREMARK As String
    Public Property FASTRDT As Nullable(Of Date)
    Public Property FASTRTM As String
    Public Property FAFINDT As Nullable(Of Date)
    Public Property FAFINTM As String
    Public Property FWOAGDQTY As Nullable(Of Double)
    Public Property FWOARJQTY As Nullable(Of Double)
    Public Property FENTDATE As Nullable(Of Date)
    Public Property FOPAGDQTY As Nullable(Of Double)
    Public Property FOPARJQTY As Nullable(Of Double)
    Public Property FUPDBY As String
    Public Property FUMATLCOST As Nullable(Of Double)
    Public Property FUDL As Nullable(Of Double)
    Public Property FUFOH As Nullable(Of Double)
    Public Property FUVOH As Nullable(Of Double)
    Public Property FAMATLCOST As Nullable(Of Double)
    Public Property FADL As Nullable(Of Double)
    Public Property FAFOH As Nullable(Of Double)
    Public Property FAVOH As Nullable(Of Double)
    Public Property FEXPDATE As Nullable(Of Date)
    Public Property FREPRJNO As String

End Class
