'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PD23JBO2
    Public Property FJONO As String
    Public Property FITEMNO As String
    Public Property FJODESC As String
    Public Property FJODESCTY As String
    Public Property FNOOPERAT As String
    Public Property FMEMONO As String
    Public Property FMEMODATE As Nullable(Of Date)
    Public Property FENTBY As String
    Public Property FNOTICETO As String
    Public Property FSUBJECT As String
    Public Property FADDMAIL As String
    Public Property FMEMOTIME As String

End Class
