'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PD24RSL3
    Public Property FREQNO As String
    Public Property FREQDATE As Nullable(Of Date)
    Public Property FREQTYPE As String
    Public Property FSHCODE As String
    Public Property FITEMNO As String
    Public Property FMACHCODE As String
    Public Property FMOLDNO As String
    Public Property FMOLDNONEW As String
    Public Property FSTTIME As String
    Public Property FFNTIME As String
    Public Property FPRBCODE As String
    Public Property FREMARK As String
    Public Property FREQBY As String
    Public Property FAPPBY As String
    Public Property FCUAPPBY As String
    Public Property FSOLVBY As String
    Public Property FSOLVMETH As String
    Public Property FWONO As String
    Public Property FLOTNO As String
    Public Property FOPSEQ As String

End Class
