'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PD50PDPN
    Public Property FPLANNO As String
    Public Property FPLANDATE As Nullable(Of Date)
    Public Property FPLANBY As String
    Public Property FREQDTFR As Nullable(Of Date)
    Public Property FREQDTTO As Nullable(Of Date)
    Public Property FPDLINE As String
    Public Property FPLANSTEP As String
    Public Property FPLANCD As String
    Public Property FPLANYEAR As String
    Public Property FREPRJNO As String

End Class
