'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PD51PDPH
    Public Property FPLANNO As String
    Public Property FPDCODE As String
    Public Property FPDQTY As Nullable(Of Double)
    Public Property FREWKGD As String
    Public Property FREWKQTY As Nullable(Of Double)
    Public Property FWIPQTY As Nullable(Of Double)

End Class
