'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PD52MRPN
    Public Property FMATLCODE As String
    Public Property FMDATE As Nullable(Of Date)
    Public Property FREQQTY As Nullable(Of Double)
    Public Property FORDQTY As Nullable(Of Double)
    Public Property FRECQTY As Nullable(Of Double)
    Public Property FBKOQTY As Nullable(Of Double)
    Public Property FBOOKQTY As Nullable(Of Double)
    Public Property FDECQTY As Nullable(Of Double)
    Public Property FPLANNO As String
    Public Property FSONO As String
    Public Property FSOITEMNO As String
    Public Property FPDCODE As String
    Public Property FOPSEQ As String
    Public Property FPRODUCEYN As String
    Public Property FPRNO As String
    Public Property FPRITEMNO As String
    Public Property FUCOST As Nullable(Of Double)
    Public Property FQUSE As Nullable(Of Double)
    Public Property FPSCR As Nullable(Of Double)
    Public Property FUPDBY As String
    Public Property FUPDDATE As Nullable(Of Date)
    Public Property FMATLNOTE As String

End Class
