'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RD01CUST
    Public Property FCUCODE As String
    Public Property FCUNAME As String
    Public Property FCUNAMET As String
    Public Property FCUSHORTNM As String
    Public Property FMEMBERCD As String
    Public Property FGRPCODE As String
    Public Property FADD1 As String
    Public Property FADD2 As String
    Public Property FADD3 As String
    Public Property FPROVINCE As String
    Public Property FPOSTAL As String
    Public Property FPROVCD As String
    Public Property FCITYCD As String
    Public Property FTEL As String
    Public Property FTELEX As String
    Public Property FFAX As String
    Public Property FMOBILE As String
    Public Property FEMAIL As String
    Public Property FMD As String
    Public Property FMDTEL As String
    Public Property FCONT As String
    Public Property FTELC As String
    Public Property FROUTE As String
    Public Property FSMCODE As String
    Public Property FSMCODE2 As String
    Public Property FSLAREA As String
    Public Property FSLROUTE As String
    Public Property FCATEGORY As String
    Public Property FACCD As String
    Public Property FCULOCAT As String
    Public Property FCRLIMIT As Nullable(Of Double)
    Public Property FCRTERMTY As String
    Public Property FCRTERM As Nullable(Of Double)
    Public Property FCRTERMV As Nullable(Of Double)
    Public Property FSTDATE As Nullable(Of Date)
    Public Property FCRGRADE As String
    Public Property FPAYTYPE As String
    Public Property FCUSLOCK As String
    Public Property FNOTE As String
    Public Property FORDDISC As Nullable(Of Double)
    Public Property FCASHDISC As Nullable(Of Double)
    Public Property FENTBY As String
    Public Property FENTDATE As Nullable(Of Date)
    Public Property FENTTYPE As String
    Public Property FUPDBY As String
    Public Property FUPDDATE As Nullable(Of Date)
    Public Property FCONTCODE As String
    Public Property FNOTUSE As String
    Public Property FVATYN As String
    Public Property FBANKACC As String
    Public Property FCSTATUS As Nullable(Of Byte)
    Public Property CUSTTYPE As Nullable(Of Integer)
    Public Property PROJECTNO As String
    Public Property SERIALNOF As String
    Public Property STATUSRESALE As Nullable(Of Integer)
    Public Property CLOSEDATE As Nullable(Of Date)
    Public Property FTELNOUPDATE As String
    Public Property StmDate As Nullable(Of Date)
    Public Property FBRANCHTYPE As Nullable(Of Integer)
    Public Property FBRANCHCODE As String
    Public Property FBRANCHNAME As String

End Class
