'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RD01CXRF
    Public Property FCUCODE As String
    Public Property FCUXREF As String
    Public Property FDESC As String
    Public Property FDMARK As String
    Public Property FDMARK2 As String
    Public Property FADD1 As String
    Public Property FADD2 As String
    Public Property FADD3 As String
    Public Property FBLDEST As String
    Public Property FFNDEST As String
    Public Property FDOCTO As String
    Public Property FSHIPROUTE As String

End Class
