'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RD05BANK
    Public Property FBKCODE As String
    Public Property FBKNAME As String
    Public Property FBKNAMET As String
    Public Property FBRANCH As String
    Public Property FBKACNO As String
    Public Property FACCD As String
    Public Property FBFAMT As Nullable(Of Double)
    Public Property FDKFORM As String
    Public Property FCOMPID As String
    Public Property FBRNCD As String
    Public Property FBATCHNO As String
    Public Property FPRNMARK As String
    Public Property FINTRATE As Nullable(Of Double)
    Public Property FCRLIMIT As Nullable(Of Double)
    Public Property FDKCHARGE As String
    Public Property SAPAccountCode As String

End Class
