'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RD11CHR3
    Public Property FVOUNO As String
    Public Property FCASHTYPE As String
    Public Property FCHQAMT As Nullable(Of Double)
    Public Property FCASHAMT As Nullable(Of Double)
    Public Property FBKCHQ As String
    Public Property FCHQNO As String
    Public Property FCHQDATE As Nullable(Of Date)
    Public Property FDUEDATE As Nullable(Of Date)
    Public Property FBKCHQBR As String
    Public Property FBKCHQAC As String
    Public Property FTYCLEAR As String
    Public Property FCHQTYPE As String
    Public Property FBKCHQBRCODE As String

End Class
