'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RD12PIN1
    Public Property FYEAR As String
    Public Property FMDATE As Nullable(Of Date)
    Public Property FVOUCD As String
    Public Property FVOUNO As String
    Public Property FVOUDATE As Nullable(Of Date)
    Public Property FCASHIERCD As String
    Public Property FBKCODE As String
    Public Property FBKACNO As String
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FCASHAMT As Nullable(Of Double)
    Public Property FCHQAMT As Nullable(Of Double)
    Public Property FRBKCHARGE As Nullable(Of Double)
    Public Property FBKCHARGE As Nullable(Of Double)
    Public Property FACCD1 As String
    Public Property FPRJCODE As String
    Public Property FBATCHNO As String
    Public Property FUPDFLAG As String
    Public Property FUPDBY As String
    Public Property FCOMPLETE As Nullable(Of Double)
    Public Property FGLFLAG As String

End Class
