'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RD14RST1
    Public Property FVOUNO As String
    Public Property FMDATE As Nullable(Of Date)
    Public Property FCUCODE As String
    Public Property FKEEPDATE As Nullable(Of Date)
    Public Property FENTDATE As Nullable(Of Date)
    Public Property FPRJCODE As String

End Class
