'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RD14RST2
    Public Property FVOUNO As String
    Public Property FREFNO As String
    Public Property FAMOUNT As Nullable(Of Double)

End Class
