'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RD17RCT1
    Public Property FYEAR As String
    Public Property FPRDNO As String
    Public Property FTRNCD As String
    Public Property FTRNNO As String
    Public Property FTRNDATE As Nullable(Of Date)
    Public Property FRECEIPTCD As String
    Public Property FRECEIPTNO As String
    Public Property FRECTDATE As Nullable(Of Date)
    Public Property FDES As String
    Public Property FCUCODE As String
    Public Property FSMCODE As String
    Public Property FENTAMOUNT As Nullable(Of Double)
    Public Property FOTHAMT1 As Nullable(Of Double)
    Public Property FORDDISC As Nullable(Of Double)
    Public Property FORDAMT As Nullable(Of Double)
    Public Property FCASHDISC As Nullable(Of Double)
    Public Property FCASHAMT As Nullable(Of Double)
    Public Property FOTHVAT1 As Nullable(Of Double)
    Public Property FENTDATE As Nullable(Of Date)
    Public Property FDOCSTATUS As String
    Public Property FPVAT As Nullable(Of Double)
    Public Property FCNETAMT As String

End Class
