'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RD18CTR2
    Public Property FVOUNO As String
    Public Property FCASHTYPE As String
    Public Property FBKCHQ As String
    Public Property FCHQNO As String
    Public Property FCHQDATE As Nullable(Of Date)
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FDUEDATE As Nullable(Of Date)
    Public Property FBKCHQBR As String
    Public Property FTYCLEAR As String
    Public Property FACTFLAG As String

End Class
