'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RD21ARDL
    Public Property FYEAR As String
    Public Property FMDATE As Nullable(Of Date)
    Public Property FVOUNO As String
    Public Property FVOUDATE As Nullable(Of Date)
    Public Property FVOUTYPE As String
    Public Property FSUBTYPE As String
    Public Property FCUCODE As String
    Public Property FREFNO As String
    Public Property FCREDITCD As String
    Public Property FDIVCODE As String
    Public Property FTYCODE As String
    Public Property FSMCODE As String
    Public Property FDUEDATE As Nullable(Of Date)
    Public Property FDES As String
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FPRJCODE As String
    Public Property FENTDATE As Nullable(Of Date)
    Public Property FAGRNO As String
    Public Property FCOLPRDNO As String
    Public Property FPFEEDAY As Nullable(Of Double)
    Public Property FPAYTYPE As String
    Public Property FBKCHQ As String
    Public Property FCHQNO As String
    Public Property FCHQDATE As Nullable(Of Date)
    Public Property FBKCODE As String
    Public Property FBILLNO As String
    Public Property FBILLDATE As Nullable(Of Date)
    Public Property FKEEPDATE As Nullable(Of Date)
    Public Property FQTY As Nullable(Of Double)

End Class
