'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RD22ARWK
    Public Property FCUCODE As String
    Public Property FREFNO As String
    Public Property FCREDITCD As String
    Public Property FAGRNO As String
    Public Property FCOLPRDNO As String
    Public Property FMDATE As Nullable(Of Date)
    Public Property FVOUTYPE As String
    Public Property FSUBTYPE As String
    Public Property FDUEDATE As Nullable(Of Date)
    Public Property FINVAMT As Nullable(Of Double)
    Public Property FBFAMT As Nullable(Of Double)
    Public Property FDBAMT As Nullable(Of Double)
    Public Property FCRAMT As Nullable(Of Double)
    Public Property FCFAMT As Nullable(Of Double)
    Public Property FPRJCODE As String
    Public Property FENTDATE As Nullable(Of Date)
    Public Property FUPDBY As String
    Public Property FSMCODE As String
    Public Property FDIVCODE As String
    Public Property FTYCODE As String
    Public Property FDES As String
    Public Property FBILLNO As String
    Public Property FBILLDATE As Nullable(Of Date)
    Public Property FKEEPDATE As Nullable(Of Date)
    Public Property FRECEIPTNO As String
    Public Property FPFEEDAY As Nullable(Of Double)

End Class
