'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RD24CLRG
    Public Property FBILLNO As String
    Public Property FBILLDATE As Nullable(Of Date)
    Public Property FCUCODE As String
    Public Property FKEEPDATE As Nullable(Of Date)
    Public Property FREFNO As String
    Public Property FREFAMT As Nullable(Of Double)

End Class
