'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RD26ORRG
    Public Property FYEAR As String
    Public Property FRECEIPTNO As String
    Public Property FRECTDATE As Nullable(Of Date)
    Public Property FREFNO As String
    Public Property FAGRNO As String
    Public Property FCOLPRDNO As String
    Public Property FCREDITCD As String
    Public Property FRECTTYPE As String
    Public Property FDOCSTATUS As String
    Public Property FRVNO As String
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FAGOODS As Nullable(Of Double)
    Public Property FAVAT As Nullable(Of Double)
    Public Property FENTTYPE As String
    Public Property FPAYINNO As String
    Public Property FAPPFLAG As String
    Public Property FAPPBY As String
    Public Property FAPPDATE As Nullable(Of Date)

End Class
