'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RD40CRT2
    Public Property FCUCODE As String
    Public Property FMDATE1 As Date
    Public Property FMDATE2 As Nullable(Of Date)
    Public Property FPAIDDATE As Nullable(Of Date)

End Class
