'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SAPConvItem
    Public Property FRINDX As Integer
    Public Property ConversionDate As Nullable(Of Date)
    Public Property TransCD As String
    Public Property FREPRJNO As String
    Public Property FSERIALNO As String
    Public Property FCONTCODE As String
    Public Property FVOUNO As String
    Public Property FAMOUNT As Nullable(Of Double)

End Class
