'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SAPInfPostMonthEnd
    Public Property FRINDX As Integer
    Public Property SAPDailyDate As Nullable(Of Date)
    Public Property YEARCD As Nullable(Of Integer)
    Public Property MONTHCD As Nullable(Of Integer)
    Public Property ProjectNo As String
    Public Property UnitNo As String
    Public Property FVOUNO As String
    Public Property FAGRNO As String
    Public Property FCUCODE As String
    Public Property H_ItemNumber As Nullable(Of Integer)
    Public Property H_CompanyCode As String
    Public Property H_DocumentType As String
    Public Property H_DocumentDate As Nullable(Of Date)
    Public Property H_PostingDate As Nullable(Of Date)
    Public Property H_Reference As String
    Public Property H_DocheaderText As String
    Public Property H_Currency As String
    Public Property PostingKey As String
    Public Property Account As String
    Public Property CustomerCode As String
    Public Property SpecialGL As String
    Public Property Amount As Nullable(Of Double)
    Public Property BusinessPlace As String
    Public Property WBS As String
    Public Property Assignment As String
    Public Property Reference1 As String
    Public Property Reference2 As String
    Public Property TextLine As String
    Public Property TextFileLine As String

End Class
