'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SCANASSET
    Public Property SFILENAME As String
    Public Property TRNDATE As Decimal
    Public Property FREPRJNO As String
    Public Property ASSETNO As String
    Public Property ASSETNAME As String
    Public Property FPCLANDOWN As String
    Public Property FDPCODE As String
    Public Property FSECCODE As String
    Public Property FSECNAME As String
    Public Property FLCNO As String
    Public Property OLDFREPRJNO As String
    Public Property OLDFDPCODE As String
    Public Property OLDFSECCODE As String
    Public Property OLDFSECNAME As String
    Public Property OLDFLCNO As String
    Public Property TIMESCAN As String
    Public Property STATUS As String
    Public Property SCAN As String
    Public Property NONASSET As String

End Class
