'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SD04PDBG
    Public Property FPDCODE As String
    Public Property FACCD As String
    Public Property FYEAR As String
    Public Property FUPDATEDT As Nullable(Of Date)
    Public Property FUSEFLAG As String
    Public Property FBGAMT01 As Nullable(Of Double)
    Public Property FBGAMT02 As Nullable(Of Double)
    Public Property FBGAMT03 As Nullable(Of Double)
    Public Property FBGAMT04 As Nullable(Of Double)
    Public Property FBGAMT05 As Nullable(Of Double)
    Public Property FBGAMT06 As Nullable(Of Double)
    Public Property FBGAMT07 As Nullable(Of Double)
    Public Property FBGAMT08 As Nullable(Of Double)
    Public Property FBGAMT09 As Nullable(Of Double)
    Public Property FBGAMT10 As Nullable(Of Double)
    Public Property FBGAMT11 As Nullable(Of Double)
    Public Property FBGAMT12 As Nullable(Of Double)
    Public Property FBGTOTAMT As Nullable(Of Double)
    Public Property FFLAGEDIT As String
    Public Property FUPDFLAG As String

End Class
