'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SD04INMT
    Public Property FMOVECODE As String
    Public Property FMOVEDESC As String
    Public Property FMOVESDESC As String
    Public Property FACCD As String

End Class
