'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SD05PROM1
    Public Property FRUNID As String
    Public Property FREPRJNO As String
    Public Property FPDCODE As String
    Public Property FSTARTDATE As Nullable(Of Date)
    Public Property FENDDATE As Nullable(Of Date)
    Public Property FRUNBY As String
    Public Property FRUNDATE As Nullable(Of Date)
    Public Property FUPDFLAG As String
    Public Property FUPDBY As String
    Public Property FUPDATE As Nullable(Of Date)
    Public Property FCANCEL As String
    Public Property FCALCELBY As String
    Public Property FCANCELDATE As Nullable(Of Date)

End Class
