'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SD11ICTR
    Public Property FTRNYEAR As String
    Public Property FTRNCD As String
    Public Property FTRNNO As String
    Public Property FITEMNO As String
    Public Property FYEAR As String
    Public Property FPRDNO As String
    Public Property FMDATE As Nullable(Of Date)
    Public Property FVOUCD As String
    Public Property FVOUNO As String
    Public Property FVOUDATE As Nullable(Of Date)
    Public Property FMOVECODE As String
    Public Property FSUBTYPE As String
    Public Property FGDCODE As String
    Public Property FGDCODE2 As String
    Public Property FREFNO As String
    Public Property FPRNO As String
    Public Property FPONO As String
    Public Property FCONTCODE As String
    Public Property FINVNO As String
    Public Property FLINKNO As String
    Public Property FWONO As String
    Public Property FLOTNO As String
    Public Property FPDLINE As String
    Public Property FDPCODE As String
    Public Property FSECCODE As String
    Public Property FWCCODE As String
    Public Property FJONO As String
    Public Property FACCD As String
    Public Property FBINLOC As String
    Public Property FBINLOCTO As String
    Public Property FUPDSEQ As String
    Public Property FDIVCODE As String
    Public Property FPDCODE As String
    Public Property FREPRJNO As String
    Public Property FSERIALNO As String
    Public Property FSERIALNO2 As String
    Public Property FENTQTY As Nullable(Of Double)
    Public Property FUMCODE As String
    Public Property FENTUC As Nullable(Of Double)
    Public Property FQTY As Nullable(Of Double)
    Public Property FQTYREJ As Nullable(Of Double)
    Public Property FREFQTY As Nullable(Of Double)
    Public Property FREFQTYREJ As Nullable(Of Double)
    Public Property FUC As Nullable(Of Double)
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FTKTAX As Nullable(Of Double)
    Public Property FREMARK As String
    Public Property FENTDATE As Nullable(Of Date)
    Public Property FUSER As String
    Public Property FBATCHNO As String
    Public Property FUPDFLAG As String
    Public Property FCOMPLETE As Nullable(Of Double)
    Public Property FPRJCODE As String
    Public Property FFINALJUDG As String
    Public Property FUPDBY As String
    Public Property FPNDLFLAG As String
    Public Property FWGRECNO As String

End Class
