'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SD19PHY1
    Public Property FYEAR As String
    Public Property FPRDNO As String
    Public Property FGDCODE As String
    Public Property FVOUCD As String
    Public Property FVOUNO As String
    Public Property FMDATE As Nullable(Of Date)
    Public Property FPDCODE As String
    Public Property FQPHYCNT As Nullable(Of Double)
    Public Property FQPHYCNTS As Nullable(Of Double)
    Public Property FREFNO As String
    Public Property FMOVECODE As String
    Public Property FVOUDATE As Nullable(Of Date)
    Public Property FQTY As Nullable(Of Double)
    Public Property FQEOH As Nullable(Of Double)
    Public Property FAEOH As Nullable(Of Double)
    Public Property FCOMPLETE As Nullable(Of Double)
    Public Property FENTDATE As Nullable(Of Date)
    Public Property FPRJCODE As String
    Public Property FUSER As String
    Public Property FUPDFLAG As String
    Public Property FITEMNO As String
    Public Property FUPDBY As String
    Public Property FDIVCODE As String

End Class
