'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SD23AVCT
    Public Property FGDCODE As String
    Public Property FPDCODE As String
    Public Property FUC As Nullable(Of Double)
    Public Property FQEOH As Nullable(Of Double)
    Public Property FAEOH As Nullable(Of Double)
    Public Property FLMOVEDATE As Nullable(Of Date)

End Class
