'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SD42ACTB_Copy
    Public Property FCTRLCODE As String
    Public Property FCTRLDESC As String
    Public Property FLSLACCD As String
    Public Property FESLACCD As String
    Public Property FACCD121 As String
    Public Property FACCD122 As String
    Public Property FACCD21 As String
    Public Property FACCD221 As String
    Public Property FACCD222 As String
    Public Property FACCD223 As String
    Public Property FACCD224 As String
    Public Property FACCD24 As String
    Public Property FACCD25 As String
    Public Property FACCD26 As String
    Public Property FACCD32 As String
    Public Property FUPDDATE As Nullable(Of Date)
    Public Property FACCD27 As String
    Public Property FACCD21E As String
    Public Property FACCD121E As String
    Public Property FACCD322 As String

End Class
