'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SM_COM_QUARTER
    Public Property FSMCODE As String
    Public Property FSMNAME As String
    Public Property POSITION As String
    Public Property CALYEAR As String
    Public Property QUARTER As String
    Public Property TARGETUNIT As Nullable(Of Integer)
    Public Property NETSALEUNIT As Nullable(Of Integer)
    Public Property VOIDUNIT As Nullable(Of Integer)
    Public Property PERFORMANCE As Nullable(Of Double)
    Public Property NORRATE As Nullable(Of Double)
    Public Property PERRATE As Nullable(Of Double)
    Public Property ACTUALCONTRACT As Nullable(Of Double)
    Public Property PAIDCOMCONT As Nullable(Of Double)
    Public Property NEWCOMCONT As Nullable(Of Double)
    Public Property PAYCOMCONT As Nullable(Of Double)
    Public Property PAID As String

End Class
