'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SM_COMM
    Public Property FAGRNO As String
    Public Property FREPRJNO As String
    Public Property FREPRJNAME As String
    Public Property FSERIALNO As String
    Public Property BOOKNO As String
    Public Property BOOKDATE As Nullable(Of Decimal)
    Public Property FSMCODE As String
    Public Property FSMNAME As String
    Public Property POSITION As String
    Public Property CUSTCODE As String
    Public Property CUSTNAME As String
    Public Property FMDATE As Nullable(Of Decimal)
    Public Property SALEPRICE As Nullable(Of Double)
    Public Property DISCOUNT As Nullable(Of Double)
    Public Property PROMOTION As Nullable(Of Double)
    Public Property ACTUALPRICE As Nullable(Of Double)
    Public Property COMMCONTRACT As Nullable(Of Double)
    Public Property COMMTRANSFER As Nullable(Of Double)
    Public Property NEWCOMCONTRACT As Nullable(Of Double)
    Public Property NEWCOMTRANSFER As Nullable(Of Double)
    Public Property PAID As String
    Public Property FTRNCD As String

End Class
