'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SM_TARGET
    Public Property FYEAR As String
    Public Property FREPRJNO As String
    Public Property FSMCODE As String
    Public Property FSMNAME As String
    Public Property FTYCODE As String
    Public Property UNIT1 As Nullable(Of Double)
    Public Property AMOUNT1 As Nullable(Of Double)
    Public Property UNIT2 As Nullable(Of Double)
    Public Property AMOUNT2 As Nullable(Of Double)
    Public Property UNIT3 As Nullable(Of Double)
    Public Property AMOUNT3 As Nullable(Of Double)
    Public Property UNIT4 As Nullable(Of Double)
    Public Property AMOUNT4 As Nullable(Of Double)
    Public Property UNIT5 As Nullable(Of Double)
    Public Property AMOUNT5 As Nullable(Of Double)
    Public Property UNIT6 As Nullable(Of Double)
    Public Property AMOUNT6 As Nullable(Of Double)
    Public Property UNIT7 As Nullable(Of Double)
    Public Property AMOUNT7 As Nullable(Of Double)
    Public Property UNIT8 As Nullable(Of Double)
    Public Property AMOUNT8 As Nullable(Of Double)
    Public Property UNIT9 As Nullable(Of Double)
    Public Property AMOUNT9 As Nullable(Of Double)
    Public Property UNIT10 As Nullable(Of Double)
    Public Property AMOUNT10 As Nullable(Of Double)
    Public Property UNIT11 As Nullable(Of Double)
    Public Property AMOUNT11 As Nullable(Of Double)
    Public Property UNIT12 As Nullable(Of Double)
    Public Property AMOUNT12 As Nullable(Of Double)
    Public Property UNITQ1 As Nullable(Of Double)
    Public Property AMOUNTQ1 As Nullable(Of Double)
    Public Property UNITQ2 As Nullable(Of Double)
    Public Property AMOUNTQ2 As Nullable(Of Double)
    Public Property UNITQ3 As Nullable(Of Double)
    Public Property AMOUNTQ3 As Nullable(Of Double)
    Public Property UNITQ4 As Nullable(Of Double)
    Public Property AMOUNTQ4 As Nullable(Of Double)
    Public Property UNITYEAR As Nullable(Of Double)
    Public Property AMOUNTYEAR As Nullable(Of Double)

End Class
