'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Snapt0606_SAPBI_UnitCancellation
    Public Property COM_CODE As String
    Public Property PROJ_CODE_SOFTPRO As String
    Public Property PROJ_CODE_SAP As String
    Public Property UNIT_ID As String
    Public Property CANCEL_DATE As String
    Public Property CANCEL_RES As String
    Public Property FREASONCD As String
    Public Property FRSDESC As String
    Public Property FRSGROUP As String
    Public Property RSGROUPNAME As String
    Public Property CancelPrice As Nullable(Of Double)

End Class
