'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SV_FORMPRINT
    Public Property FINDX As Integer
    Public Property PROJECTNO As String
    Public Property UNITNO As String
    Public Property FVOUNO As String
    Public Property PRINTCODE As String
    Public Property PRINTNUMBER As Nullable(Of Integer)
    Public Property FORMID As String
    Public Property PRINTBY As String
    Public Property STMDATE As Nullable(Of Date)
    Public Property STMTIME As String
    Public Property STATUSFLAG As String

End Class
