'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SV_QUESTHISR
    Public Property FRINDX As Integer
    Public Property FORMID As String
    Public Property SAVEBY As String
    Public Property StmDate As Nullable(Of Date)
    Public Property Stmtime As String

End Class
