'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class T_CAL_COUNT
    Public Property FYEAR As String
    Public Property PERIOD As Integer
    Public Property FREPRJNO As String
    Public Property CALCOUNT As Nullable(Of Integer)
    Public Property YEARMONTH As Nullable(Of Decimal)

End Class
