'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class T_MENU2
    Public Property FUSERID As String
    Public Property FMENUID As String
    Public Property FACC As Nullable(Of Integer)
    Public Property FADD As Nullable(Of Integer)
    Public Property FUPDATE As Nullable(Of Integer)
    Public Property FDELETE As Nullable(Of Integer)
    Public Property FCALC As Nullable(Of Integer)
    Public Property FPRINT As Nullable(Of Integer)

End Class
