'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class T_RATE
    Public Property FLEVEL As String
    Public Property AGRFIXRATE As Nullable(Of Double)
    Public Property AGRADDRATE As Nullable(Of Double)
    Public Property TRNFIXRATE As Nullable(Of Double)
    Public Property TRNADDRATE As Nullable(Of Double)

End Class
