'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TD11WKTM
    Public Property FMDATE As Date
    Public Property FEMPNO As String
    Public Property FWKSHCODE As String
    Public Property FTIMEIN As Nullable(Of Double)
    Public Property FTIMEOUT As Nullable(Of Double)
    Public Property FDATEIN As Nullable(Of Date)
    Public Property FDATEOUT As Nullable(Of Date)
    Public Property FNROT As String
    Public Property FNHOT As Nullable(Of Double)
    Public Property FAROT As String
    Public Property FAHOT As Nullable(Of Double)
    Public Property FNTIMEIN As Nullable(Of Double)
    Public Property FNTIMEOUT As Nullable(Of Double)
    Public Property FNDATEIN As Nullable(Of Date)
    Public Property FNDATEOUT As Nullable(Of Date)
    Public Property FNNROT As String
    Public Property FNNHOT As Nullable(Of Double)
    Public Property FNAROT As String
    Public Property FNAHOT As Nullable(Of Double)
    Public Property FCERR As String
    Public Property FATTENDCD As String
    Public Property FATTENDCD2 As String
    Public Property FATTENDHR As Nullable(Of Double)
    Public Property FPAID As String
    Public Property FHOT As Nullable(Of Double)
    Public Property FHOT1 As Nullable(Of Double)
    Public Property FHOT2 As Nullable(Of Double)
    Public Property FHOT3 As Nullable(Of Double)
    Public Property FHOT4 As Nullable(Of Double)
    Public Property FOTSHCODE As String
    Public Property FOTFOOD As Nullable(Of Double)
    Public Property FOTSHIFT As Nullable(Of Double)
    Public Property FUPDFLAG As String
    Public Property FUPDBY As String
    Public Property FCNTTOPY As Nullable(Of Double)
    Public Property FCBUDDY As Nullable(Of Double)

End Class
