'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TD21SVAT
    Public Property FVOUNO As String
    Public Property FVOUTYPE As String
    Public Property FMDATE As Nullable(Of Date)
    Public Property FCONTCODE As String
    Public Property FCONTNAME As String
    Public Property FDESC As String
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FPVAT As Nullable(Of Double)
    Public Property FAVAT As Nullable(Of Double)
    Public Property FCONDOCNO As String
    Public Property FCONDOCDT As Nullable(Of Date)
    Public Property FCONREFNO As String
    Public Property FREFNO As String
    Public Property FPRJCODE As String
    Public Property FENTTYPE As String
    Public Property FVATTYPE As String
    Public Property FRVATALC As Nullable(Of Double)
    Public Property FAVATNC As Nullable(Of Double)
    Public Property FYEAR As String
    Public Property FITEMNO As String
    Public Property FDIVCODE As String

End Class
