'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UD11PRQ1
    Public Property FYEAR As String
    Public Property FDIVCODE As String
    Public Property FPRCD As String
    Public Property FPRNO As String
    Public Property FMDATE As Nullable(Of Date)
    Public Property FDPCODE As String
    Public Property FSECCODE As String
    Public Property FCLASS As String
    Public Property FREPRJNO As String
    Public Property FREMARK As String
    Public Property FUPDFLAG As String
    Public Property FUPDBY As String
    Public Property FUPDDATE As Nullable(Of Date)
    Public Property FCURRENCY As String
    Public Property FEXRATE As Nullable(Of Double)
    Public Property FSUCODE As String
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FORDDISC As Nullable(Of Double)
    Public Property FORDAMT As Nullable(Of Double)
    Public Property FCASHDISC As Nullable(Of Double)
    Public Property FCASHAMT As Nullable(Of Double)
    Public Property FPVAT As Nullable(Of Double)
    Public Property FAVAT As Nullable(Of Double)
    Public Property FWHOREQ As String
    Public Property FDPREQ As String
    Public Property FSECREQ As String
    Public Property FCONTTRNNO As String
    Public Property FAPPBY As String
    Public Property FAPPFLAG As String
    Public Property FCUCODE As String
    Public Property FPLANNO As String
    Public Property FWHEREPO As String
    Public Property FWHEREDEL As String
    Public Property FDOCSTATUS As String
    Public Property FVOIDDATE As Nullable(Of Date)
    Public Property FVOIDBY As String
    Public Property FSULIST As String
    Public Property FBGFLAG As String
    Public Property FBGAPPBY As String
    Public Property FBGAPPDT As Nullable(Of Date)
    Public Property FUSEBGYN As String
    Public Property FVOIDREAS As String
    Public Property FPRTYPE As String
    Public Property SAPTYPER As String
    Public Property SAPSERIAL As String

End Class
