'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UD11PRQ2
    Public Property FPRNO As String
    Public Property FITEMNO As String
    Public Property FPDCODE As String
    Public Property FQTY As Nullable(Of Double)
    Public Property FUMCODE As String
    Public Property FREQDATE As Nullable(Of Date)
    Public Property FPONO As String
    Public Property FSONO As String
    Public Property FSOITEMNO As String
    Public Property FCLASS As String
    Public Property FDESC As String
    Public Property FUP As Nullable(Of Double)
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FENTQTY As Nullable(Of Double)
    Public Property FENTUP As Nullable(Of Double)
    Public Property FVOIDQTY As Nullable(Of Double)
    Public Property FLCNO As String
    Public Property FITEMREM As String
    Public Property FREFVOUNO As String
    Public Property FREFUNITNO As String
    Public Property FREFAMOUNT As Nullable(Of Double)
    Public Property FPLANREAMRK As String
    Public Property IsExport As String

End Class
