'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UD14RRF1
    Public Property FTRNYEAR As String
    Public Property FTRNCD As String
    Public Property FTRNNO As String
    Public Property FDIVCODE As String
    Public Property FREPRJNO As String
    Public Property FVOUDATE As Nullable(Of Date)
    Public Property FYEAR As String
    Public Property FMDATE As Nullable(Of Date)
    Public Property FRRCD As String
    Public Property FRRNO As String
    Public Property FGDCODE As String
    Public Property FSUCODE As String
    Public Property FAPACCD As String
    Public Property FINVNO As String
    Public Property FINVDATE As Nullable(Of Date)
    Public Property FBLNO As String
    Public Property FSRRNO As String
    Public Property FDDATE As Nullable(Of Date)
    Public Property FPTERM As Nullable(Of Double)
    Public Property FDUEDATE As Nullable(Of Date)
    Public Property FCURRENCY As String
    Public Property FEXRATE As Nullable(Of Double)
    Public Property FTQTY As Nullable(Of Double)
    Public Property FALLCBY As String
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FDISCOUNT As Nullable(Of Double)
    Public Property FCLEARING As Nullable(Of Double)
    Public Property FFREIGHT As Nullable(Of Double)
    Public Property FTAX As Nullable(Of Double)
    Public Property FAVAT As Nullable(Of Double)
    Public Property FINSTALL As Nullable(Of Double)
    Public Property FINSUR As Nullable(Of Double)
    Public Property FOTHER As Nullable(Of Double)
    Public Property FACCD1 As String
    Public Property FACCD2 As String
    Public Property FACCD3 As String
    Public Property FACCD4 As String
    Public Property FACCD5 As String
    Public Property FACCD6 As String
    Public Property FENTDATE As Nullable(Of Date)
    Public Property FUPDFLAG As String
    Public Property FUPDBY As String
    Public Property FCOMPLETE As Nullable(Of Double)
    Public Property FPVAT As Nullable(Of Double)
    Public Property FREMARK1 As String
    Public Property FREMARK2 As String
    Public Property FDOCSTATUS As String
    Public Property FVOIDNO As String
    Public Property FVOIDDATE As Nullable(Of Date)
    Public Property FVOIDBY As String
    Public Property FRVATALC As Nullable(Of Double)
    Public Property FBATCHNO As String

End Class
