'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UD22PCLG
    Public Property FMDATE As Nullable(Of Date)
    Public Property FDIVCODE As String
    Public Property FVOUNO As String
    Public Property FVOUDATE As Nullable(Of Date)
    Public Property FMOVECODE As String
    Public Property FPONO As String
    Public Property FPOITEMNO As String
    Public Property FSUCODE As String
    Public Property FCURRENCY As String
    Public Property FEXRATE As Nullable(Of Double)
    Public Property FITEMNO As String
    Public Property FRRNO As String
    Public Property FRRITEMNO As String
    Public Property FPDCODE As String
    Public Property FQTY As Nullable(Of Double)
    Public Property FUP As Nullable(Of Double)
    Public Property FAMOUNT As Nullable(Of Double)
    Public Property FADISC1 As Nullable(Of Double)
    Public Property FADISC2 As Nullable(Of Double)
    Public Property FAVAT As Nullable(Of Double)
    Public Property FGDCODE As String
    Public Property FRRUP As Nullable(Of Double)
    Public Property FRRGAMT As Nullable(Of Double)
    Public Property FRRADISC1 As Nullable(Of Double)
    Public Property FRRADISC2 As Nullable(Of Double)
    Public Property FRRFREIGHT As Nullable(Of Double)
    Public Property FRRCLEAR As Nullable(Of Double)
    Public Property FRRTAX As Nullable(Of Double)
    Public Property FRRINSTALL As Nullable(Of Double)
    Public Property FRRINSUR As Nullable(Of Double)
    Public Property FRROTHER As Nullable(Of Double)
    Public Property FRRAVAT As Nullable(Of Double)
    Public Property FRRAVATNC As Nullable(Of Double)
    Public Property SAPPO As String
    Public Property SAPITEMNO As String

End Class
