'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UD23RCL1
    Public Property FYEAR As String
    Public Property FPRDNO As String
    Public Property FMDATE As Nullable(Of Date)
    Public Property FVOUNO As String
    Public Property FVOUDATE As Nullable(Of Date)
    Public Property FVOUTYPE As String
    Public Property FSUCODE As String
    Public Property FAPACCD As String
    Public Property FCONTNAME As String
    Public Property FSUDOCNO As String
    Public Property FSUDOCDATE As Nullable(Of Date)
    Public Property FSUREFNO As String
    Public Property FCREDITCD As String
    Public Property FCOLPRDNO As String
    Public Property FDUEDATE As Nullable(Of Date)
    Public Property FBLNO As String
    Public Property FDES As String
    Public Property FTOTAMT As Nullable(Of Double)
    Public Property FPVAT As Nullable(Of Double)
    Public Property FAVAT As Nullable(Of Double)
    Public Property FAVALUE As Nullable(Of Double)
    Public Property FPRJCODE As String
    Public Property FENTTYPE As String
    Public Property FDIVCODE As String
    Public Property FTYCODE As String
    Public Property FCURRENCY As String
    Public Property FEXRATE As Nullable(Of Double)
    Public Property FRVATALC As Nullable(Of Double)
    Public Property FAVATNC As Nullable(Of Double)

End Class
