'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_UnitDefineProject
    Public Property FREPRJNO As String
    Public Property FRESTATUS As String
    Public Property FSERIALNO As String
    Public Property FTYUNIT As String
    Public Property FPDCODE As String
    Public Property FPDNAME As String
    Public Property FPDNAMET As String
    Public Property FAREA As Nullable(Of Double)
    Public Property FADDRNO As String
    Public Property FPCPIECE As String
    Public Property FREPHASE As String
    Public Property FREZONE As String
    Public Property FREBLOCK As String
    Public Property FBUILTIN As Nullable(Of Double)
    Public Property FTOWER As String
    Public Property FFLOOR As String
    Public Property FASSETNO As String
    Public Property FSTDBUILT As Nullable(Of Double)
    Public Property FDESC As String
    Public Property e_FSTDAREA As Nullable(Of Double)
    Public Property e_FSTDBUILT As Nullable(Of Double)
    Public Property e_FDESC As String
    Public Property FRESTATUSDESC As String
    Public Property FRESTYPEDESC As String
    Public Property e_FSERIALNO As String

End Class
