'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class YD02HOLI
    Public Property FHDATE As Date
    Public Property FDESC As String
    Public Property FHTYPE As String
    Public Property FROTATE As String

End Class
