'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class YD05EMP1
    Public Property FEMPNO As String
    Public Property FPRECODE As String
    Public Property FEMPNAME As String
    Public Property FEMPNAMET As String
    Public Property FUSERID As String
    Public Property FBIRTH As Nullable(Of Date)
    Public Property FBIRTHPLC As String
    Public Property FSEX As String
    Public Property FBLOOD As String
    Public Property FNATION As String
    Public Property FRACE As String
    Public Property FRELIGION As String
    Public Property FEDUCATION As String
    Public Property FMAJORITY As String
    Public Property FYEARSGRAD As String
    Public Property FACADEMIC As String
    Public Property FYEARSEXP As Nullable(Of Double)
    Public Property FSOCIALNO As String
    Public Property FTAXID As String
    Public Property FPEOPLEID As String
    Public Property FPASSPORT As String
    Public Property FBKCODE As String
    Public Property FACCNO As String
    Public Property FADD1 As String
    Public Property FADD2 As String
    Public Property FADD3 As String
    Public Property FTEL As String
    Public Property FPOSTAL As String
    Public Property FHADD1 As String
    Public Property FHADD2 As String
    Public Property FHADD3 As String
    Public Property FHTEL As String
    Public Property FHPOSTAL As String
    Public Property FMARSTAT As String
    Public Property FNOCHIN As Nullable(Of Double)
    Public Property FNOCHNO As Nullable(Of Double)
    Public Property FPOSITION As String
    Public Property FPOSUSE As String
    Public Property FDIVCODE As String
    Public Property FDPCODE As String
    Public Property FSECCODE As String
    Public Property FSUPEMPNO As String
    Public Property FDPMG As String
    Public Property FDIVMG As String
    Public Property FPDLINE As String
    Public Property FDORI As String
    Public Property FSHCODE As String
    Public Property FROTATEYN As String
    Public Property FTMRECYN As String
    Public Property FHOLTYPE As String
    Public Property FWORKTYPE As String
    Public Property FVEHICLENO As String
    Public Property FBUSSTOPCD As String
    Public Property FCALPF As String
    Public Property FPFDATE As Nullable(Of Date)
    Public Property FPFNO As String
    Public Property FRTPF As Nullable(Of Double)
    Public Property FACPF As Nullable(Of Double)
    Public Property FRTPV As Nullable(Of Double)
    Public Property FACPV As Nullable(Of Double)
    Public Property FRETFUND As Nullable(Of Double)
    Public Property FRFBASE As Nullable(Of Double)
    Public Property FEACSOC As Nullable(Of Double)
    Public Property FCACSOC As Nullable(Of Double)
    Public Property FIDDATE As Nullable(Of Date)
    Public Property FIDDATE2 As Nullable(Of Date)
    Public Property FRSDATE As Nullable(Of Date)
    Public Property FSTATUS As String
    Public Property FPROVTERM As Nullable(Of Double)
    Public Property FCONFYN As String
    Public Property FCONFDATE As Nullable(Of Date)
    Public Property FEMPCLASS As String
    Public Property FEMPLEVEL As String
    Public Property FTYEMP As String
    Public Property FTYPAY As String
    Public Property FCASEPAY As String
    Public Property FTYTAX As String
    Public Property FBSALARY As Nullable(Of Double)
    Public Property FEFFDATE As Nullable(Of Date)
    Public Property FBOTRATE As Nullable(Of Double)
    Public Property FBIPOSIT As Nullable(Of Double)
    Public Property FBITRANS As Nullable(Of Double)
    Public Property FBIOTHER2 As Nullable(Of Double)
    Public Property FPAYMSCOPE As String
    Public Property FPAYFOOD As String
    Public Property FPAYTRANS As String
    Public Property FPAYOTCD As String
    Public Property FPAYREWARD As String
    Public Property FPOSALLWYN As String
    Public Property FYOINCOME As Nullable(Of Double)
    Public Property FYOTAX As Nullable(Of Double)
    Public Property FYOSOCIAL As Nullable(Of Double)
    Public Property FYOINSUR As Nullable(Of Double)
    Public Property FYODONAT As Nullable(Of Double)
    Public Property FYOINTER As Nullable(Of Double)
    Public Property FOBSALARY As Nullable(Of Double)
    Public Property FLYSALARY As Nullable(Of Double)
    Public Property FCALREWARD As String
    Public Property FALEAVE2 As Nullable(Of Double)
    Public Property FANLRIGHTS As String
    Public Property FANLTYPE As String
    Public Property FALEAVE3 As Nullable(Of Double)
    Public Property FACLEAVE3 As Nullable(Of Double)
    Public Property FFSTLEAVE3 As Nullable(Of Double)
    Public Property FOTHLEAVE3 As Nullable(Of Double)
    Public Property FUPDATE As String
    Public Property FRLEVEL As String
    Public Property FHOUSERGNO As String
    Public Property FHOUSEDED As Nullable(Of Double)
    Public Property FPRDEQPM As String
    Public Property FCOMCODE As String
    Public Property FYEAR As String
    Public Property FPRDNO As String
    Public Property FCNTPEMP As Nullable(Of Double)
    Public Property FPRNMARK As String
    Public Property FHOUSEALLW As Nullable(Of Double)
    Public Property FPFLOANNO As String
    Public Property FPFLOANAMT As Nullable(Of Double)

End Class
