'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class YD06EMLV
    Public Property FEMPLEVEL As String
    Public Property FRCOLA As Nullable(Of Double)
    Public Property FRATTEND1 As Nullable(Of Double)
    Public Property FRATTEND2 As Nullable(Of Double)
    Public Property FPOSITALLW As Nullable(Of Double)
    Public Property FRTRANS As Nullable(Of Double)
    Public Property FLEVELNM As String
    Public Property FSALMIN As Nullable(Of Double)
    Public Property FSALMID As Nullable(Of Double)
    Public Property FSALMAX As Nullable(Of Double)
    Public Property FMEDBUDG As Nullable(Of Double)
    Public Property FMEDBUDG2 As Nullable(Of Double)
    Public Property FMEDBUDGO As Nullable(Of Double)
    Public Property FMEDBUDG2O As Nullable(Of Double)
    Public Property FRLEVEL As String
    Public Property FPRNMARK As String

End Class
