'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class YD07ACTB
    Public Property FDIVCODE As String
    Public Property FDPCODE As String
    Public Property FSECCODE As String
    Public Property FEMPCLASS As String
    Public Property FCTRLCODE As String
    Public Property FACCD1 As String
    Public Property FACCD2 As String
    Public Property FACCD3 As String
    Public Property FACCD4 As String
    Public Property FACCD5 As String
    Public Property FACCD6 As String
    Public Property FACCD6_2 As String
    Public Property FACCD6_3 As String
    Public Property FACCD7 As String
    Public Property FACCD8 As String
    Public Property FACCD9 As String
    Public Property FACCD10 As String
    Public Property FACCD11 As String
    Public Property FACCD12 As String
    Public Property FACCD13 As String
    Public Property FACCD14 As String
    Public Property FACCD15 As String
    Public Property FACCD16 As String
    Public Property FACCD17 As String
    Public Property FACCD18 As String
    Public Property FACCD19 As String
    Public Property FACCD20 As String
    Public Property FACCD21 As String
    Public Property FACCD22 As String
    Public Property FACCD99 As String
    Public Property FIACCD1 As String
    Public Property FIACCD2 As String
    Public Property FIACCD3 As String
    Public Property FIACCD4 As String
    Public Property FIACCD5 As String
    Public Property FIACCD6 As String
    Public Property FIACCD6_2 As String
    Public Property FIACCD6_3 As String
    Public Property FIACCD7 As String
    Public Property FIACCD8 As String
    Public Property FIACCD9 As String
    Public Property FIACCD10 As String
    Public Property FIACCD11 As String
    Public Property FIACCD12 As String
    Public Property FIACCD13 As String
    Public Property FIACCD14 As String
    Public Property FIACCD15 As String
    Public Property FIACCD16 As String
    Public Property FIACCD17 As String
    Public Property FIACCD18 As String
    Public Property FIACCD19 As String
    Public Property FIACCD20 As String
    Public Property FIACCD21 As String
    Public Property FIACCD22 As String
    Public Property FIACCD99 As String

End Class
