'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class YD11PRTR
    Public Property FYEAR As String
    Public Property FPRNO As String
    Public Property FTYPAY As String
    Public Property FEMPNO As String
    Public Property FBONUSFLAG As String
    Public Property FREG As Nullable(Of Double)
    Public Property FREG0 As Nullable(Of Double)
    Public Property FNOW As Nullable(Of Double)
    Public Property FHOL As Nullable(Of Double)
    Public Property FHOL0 As Nullable(Of Double)
    Public Property FLEAVE1 As Nullable(Of Double)
    Public Property FLEAVE2 As Nullable(Of Double)
    Public Property FLEAVE3 As Nullable(Of Double)
    Public Property FLEAVE4 As Nullable(Of Double)
    Public Property FLEAVE5 As Nullable(Of Double)
    Public Property FLEAVE6 As Nullable(Of Double)
    Public Property FLEAVEO As Nullable(Of Double)
    Public Property FULEAVE1 As Nullable(Of Double)
    Public Property FULEAVE2 As Nullable(Of Double)
    Public Property FULEAVE3 As Nullable(Of Double)
    Public Property FULEAVE4 As Nullable(Of Double)
    Public Property FULEAVE5 As Nullable(Of Double)
    Public Property FULEAVE6 As Nullable(Of Double)
    Public Property FLATE As Nullable(Of Double)
    Public Property FLATE2 As Nullable(Of Double)
    Public Property FULATE As Nullable(Of Double)
    Public Property FULEAVEO As Nullable(Of Double)
    Public Property FOT1 As Nullable(Of Double)
    Public Property FOT2 As Nullable(Of Double)
    Public Property FOT3 As Nullable(Of Double)
    Public Property FOT4 As Nullable(Of Double)
    Public Property FSOT1 As Nullable(Of Double)
    Public Property FSOT2 As Nullable(Of Double)
    Public Property FSOT3 As Nullable(Of Double)
    Public Property FSOT4 As Nullable(Of Double)
    Public Property FOTSPEC As Nullable(Of Double)
    Public Property FFOOD As Nullable(Of Double)
    Public Property FTRANS As Nullable(Of Double)
    Public Property FADJSOC As Nullable(Of Double)
    Public Property FSD05 As Nullable(Of Double)
    Public Property FDEXPAY As Nullable(Of Double)
    Public Property FBUDDY As Nullable(Of Double)
    Public Property FSUSP As Nullable(Of Double)
    Public Property FRFLV1 As Nullable(Of Double)
    Public Property FRFLV3 As Nullable(Of Double)
    Public Property FSHIFT As Nullable(Of Double)
    Public Property FSDANL As Nullable(Of Double)
    Public Property FBONUS2 As Nullable(Of Double)
    Public Property FBONUS3 As Nullable(Of Double)
    Public Property FIREG As Nullable(Of Double)
    Public Property FIPOSIT As Nullable(Of Double)
    Public Property FIOT1 As Nullable(Of Double)
    Public Property FIOT2 As Nullable(Of Double)
    Public Property FIOT3 As Nullable(Of Double)
    Public Property FIOT4 As Nullable(Of Double)
    Public Property FIPOT1 As Nullable(Of Double)
    Public Property FIPOT2 As Nullable(Of Double)
    Public Property FIPOT3 As Nullable(Of Double)
    Public Property FIPOT4 As Nullable(Of Double)
    Public Property FISD05 As Nullable(Of Double)
    Public Property FIATTEND As Nullable(Of Double)
    Public Property FIINCENT As Nullable(Of Double)
    Public Property FICOMM As Nullable(Of Double)
    Public Property FICOLA As Nullable(Of Double)
    Public Property FITRAN As Nullable(Of Double)
    Public Property FISHIFT As Nullable(Of Double)
    Public Property FIREWARD As Nullable(Of Double)
    Public Property FIBONUS As Nullable(Of Double)
    Public Property FIBONUSQ2 As Nullable(Of Double)
    Public Property FIBONUS2 As Nullable(Of Double)
    Public Property FIBONUSQ3 As Nullable(Of Double)
    Public Property FIBONUS3 As Nullable(Of Double)
    Public Property FIMSCOPE As Nullable(Of Double)
    Public Property FIFOOD As Nullable(Of Double)
    Public Property FIHOUSE As Nullable(Of Double)
    Public Property FITAX As Nullable(Of Double)
    Public Property FIOTHER1 As Nullable(Of Double)
    Public Property FIOTHER2 As Nullable(Of Double)
    Public Property FIOTHER3 As Nullable(Of Double)
    Public Property FIOTHER4 As Nullable(Of Double)
    Public Property FIOTHERAC1 As String
    Public Property FIOTHERAC2 As String
    Public Property FIOTHERAC3 As String
    Public Property FIOTHERAC4 As String
    Public Property FIOTHERD1 As String
    Public Property FIOTHERD2 As String
    Public Property FIOTHERD3 As String
    Public Property FIOTHERD4 As String
    Public Property FIOTHERH4 As Nullable(Of Double)
    Public Property FDREG As Nullable(Of Double)
    Public Property FDPOSIT As Nullable(Of Double)
    Public Property FDOT1 As Nullable(Of Double)
    Public Property FDOT2 As Nullable(Of Double)
    Public Property FDOT3 As Nullable(Of Double)
    Public Property FDOT4 As Nullable(Of Double)
    Public Property FDPOT1 As Nullable(Of Double)
    Public Property FDPOT2 As Nullable(Of Double)
    Public Property FDPOT3 As Nullable(Of Double)
    Public Property FDPOT4 As Nullable(Of Double)
    Public Property FDSD05 As Nullable(Of Double)
    Public Property FDATTEND As Nullable(Of Double)
    Public Property FDINCENT As Nullable(Of Double)
    Public Property FDCOMM As Nullable(Of Double)
    Public Property FDCOLA As Nullable(Of Double)
    Public Property FDTRAN As Nullable(Of Double)
    Public Property FDSHIFT As Nullable(Of Double)
    Public Property FDREWARD As Nullable(Of Double)
    Public Property FDBONUS As Nullable(Of Double)
    Public Property FDMSCOPE As Nullable(Of Double)
    Public Property FDFOOD As Nullable(Of Double)
    Public Property FDHOUSE As Nullable(Of Double)
    Public Property FDTAX As Nullable(Of Double)
    Public Property FDLOAN As Nullable(Of Double)
    Public Property FDADVANCE As Nullable(Of Double)
    Public Property FDPF As Nullable(Of Double)
    Public Property FDSOCIAL As Nullable(Of Double)
    Public Property FDNOW As Nullable(Of Double)
    Public Property FDLATE As Nullable(Of Double)
    Public Property FDOTHER1 As Nullable(Of Double)
    Public Property FDOTHER2 As Nullable(Of Double)
    Public Property FDOTHER3 As Nullable(Of Double)
    Public Property FDOTHER4 As Nullable(Of Double)
    Public Property FDOTHERAC1 As String
    Public Property FDOTHERAC2 As String
    Public Property FDOTHERAC3 As String
    Public Property FDOTHERAC4 As String
    Public Property FDOTHERD1 As String
    Public Property FDOTHERD2 As String
    Public Property FDOTHERD3 As String
    Public Property FDOTHERD4 As String
    Public Property FDOTHERH4 As Nullable(Of Double)
    Public Property FSTATUS As String
    Public Property FRSDATE As Nullable(Of Date)
    Public Property FOT1O As Nullable(Of Double)
    Public Property FOT2O As Nullable(Of Double)
    Public Property FOT3O As Nullable(Of Double)
    Public Property FOT4O As Nullable(Of Double)

End Class
