'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class YD12SMSH
    Public Property FYEAR As String
    Public Property FPRNO As String
    Public Property FEMPNO As String
    Public Property FTYPAY As String
    Public Property FSHCODE As String
    Public Property FWSHIFT As Nullable(Of Double)
    Public Property FESHIFT As Nullable(Of Double)
    Public Property FCFOOD As Nullable(Of Double)
    Public Property FCMSCOPE As Nullable(Of Double)
    Public Property FCOT1 As Nullable(Of Double)
    Public Property FCOT2 As Nullable(Of Double)
    Public Property FCOT3 As Nullable(Of Double)
    Public Property FCOT4 As Nullable(Of Double)
    Public Property FOTSHIFT As Nullable(Of Double)
    Public Property FOTFOOD As Nullable(Of Double)
    Public Property FENTTYPE As String

End Class
