'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ZFINTRAN
    Public Property FTRANSID As String
    Public Property FREPRJNO As String
    Public Property FSERIALNO As String
    Public Property FITEM As Nullable(Of Integer)
    Public Property FCUCODE As String
    Public Property FTYPE As Nullable(Of Integer)
    Public Property FACTIVE As Nullable(Of Integer)
    Public Property FREMARK As String
    Public Property FDATE As Nullable(Of Date)
    Public Property FUSERID As String

End Class
