'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ADI_ImportPriceList
    
    '''<summary>
    '''UpdatePanelMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelMain As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''hddParameterMenuID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddParameterMenuID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddReloadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddReloadGrid As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddReloadGridEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddReloadGridEdit As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpSortBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpSortBy As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpSortType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpSortType As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpPagingDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpPagingDefault As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpPageInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpPageInfo As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpSearch As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddMSGImportData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddMSGImportData As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddMSGApproveData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddMSGApproveData As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddMSGImportDataNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddMSGImportDataNo As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddMSGApproveDataNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddMSGApproveDataNo As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddMSGPleaseImport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddMSGPleaseImport As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddMSGVerify control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddMSGVerify As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddMSGOKData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddMSGOKData As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddMSGCancelData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddMSGCancelData As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddChkVerifyModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddChkVerifyModal As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpFlagSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpFlagSearch As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpLG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpLG As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpAutoCodeProjectTab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpAutoCodeProjectTab1 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpAutoNameProjectTab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpAutoNameProjectTab1 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpAutoCodePhaseTab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpAutoCodePhaseTab1 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpAutoNamePhaseTab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpAutoNamePhaseTab1 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblMain1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMain1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMain2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMain2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMain3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMain3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblsProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsProject As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlsProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlsProject As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblsPhase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsPhase As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlsPhase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlsPhase As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblsPublicUtility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsPublicUtility As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtsPublicUtility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsPublicUtility As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblsPublicUtilityM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsPublicUtilityM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblsPublicUtilityPerMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsPublicUtilityPerMonth As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtsPublicUtilityPerMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsPublicUtilityPerMonth As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblsPublicUtilityPerMonthM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsPublicUtilityPerMonthM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblsDownPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsDownPayment As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtsDownPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsDownPayment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblsFileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsFileName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtUploadFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUploadFile As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lblsBrowse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsBrowse As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''fileUploadUF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fileUploadUF As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''btnRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefresh As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnClearRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClearRefresh As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnImport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnImport As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnApproveData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApproveData As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnComment As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblColor1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblColor1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblValidate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValidate1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblColor2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblColor2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblValidate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValidate2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblColor3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblColor3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblValidate3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValidate3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblValidate4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValidate4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblHeaderImportPriceList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeaderImportPriceList As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBodyImportPriceList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBodyImportPriceList As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblHeaderVerify2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeaderVerify2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBodyVerify2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBodyVerify2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblHeaderVerify control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeaderVerify As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBodyVerify control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBodyVerify As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblHeaderVerify3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeaderVerify3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBodyVerify3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBodyVerify3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblHeaderVerify4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeaderVerify4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBodyVerify4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBodyVerify4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divRequestType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divRequestType As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rdblZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdblZone As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''grdImport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdImport As Global.System.Web.UI.WebControls.GridView
End Class
