'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MST_UsersMenuAccess
    
    '''<summary>
    '''UpdatePanelMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelMain As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''hddParameterMenuID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddParameterMenuID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddReloadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddReloadGrid As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpSortBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpSortBy As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpSortType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpSortType As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpPagingDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpPagingDefault As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddKeyID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddKeyID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpPageInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpPageInfo As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpSearch As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddMSGSaveData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddMSGSaveData As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddMSGCancelData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddMSGCancelData As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddMSGDeleteData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddMSGDeleteData As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddMSGEditData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddMSGEditData As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddMSGAddData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddMSGAddData As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpLG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpLG As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblMain1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMain1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMain2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMain2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnMain As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblMain3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMain3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnSaveTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveTemp As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnMSGSaveData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMSGSaveData As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''btnMSGCancelData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMSGCancelData As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblsUserId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsUserId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtsUserID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsUserID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMassage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMassage1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblsModule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsModule As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlsModule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlsModule As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblMassage2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMassage2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hddSelectedMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddSelectedMenu As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddSelectedMenuAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddSelectedMenuAdd As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddSelectedMenuEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddSelectedMenuEdit As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddSelectedMenuDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddSelectedMenuDelete As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddSelectedMenuApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddSelectedMenuApprove As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddSelectedMenuPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddSelectedMenuPrint As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''grdView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdView As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''hddCheckAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddCheckAll As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''grdViewRPT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdViewRPT As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''hddCheckAllRPT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddCheckAllRPT As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnReload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReload As Global.System.Web.UI.WebControls.Button
End Class
