'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ORG_Project
    
    '''<summary>
    '''UpdatePanelMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelMain As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''hddParameterMenuID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddParameterMenuID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddReloadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddReloadGrid As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpSortBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpSortBy As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpSortType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpSortType As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpPagingDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpPagingDefault As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddKeyID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddKeyID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpPageInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpPageInfo As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpSearch As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpClientID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpClientID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddTypeDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddTypeDoc As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddColumnDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddColumnDoc As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''FileUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload1 As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''hddpAutoCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpAutoCode As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpAutoName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpAutoName As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddFlanddoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddFlanddoc As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddFREQDOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddFREQDOC As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddFCONSTRDOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddFCONSTRDOC As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddFCONSTRDOC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddFCONSTRDOC1 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddFREQDOC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddFREQDOC1 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddFREQDOC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddFREQDOC2 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddFREQDOC3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddFREQDOC3 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddFREQDOC4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddFREQDOC4 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddFREQDOC5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddFREQDOC5 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddFREQDOC6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddFREQDOC6 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddFREQDOC7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddFREQDOC7 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddFREQDOC8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddFREQDOC8 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddFREQDOC9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddFREQDOC9 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddFREQDOC10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddFREQDOC10 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddMSGAddFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddMSGAddFile As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddMSGDeleteFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddMSGDeleteFile As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddMSGSaveData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddMSGSaveData As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddMSGCancelData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddMSGCancelData As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddMSGDeleteData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddMSGDeleteData As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddMSGEditData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddMSGEditData As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddMSGAddData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddMSGAddData As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddpTypeBrownser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddpTypeBrownser As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hddMasterLG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddMasterLG As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblMain1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMain1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMain2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMain2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnMain As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblMain3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMain3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnMSGAddData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMSGAddData As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''TextHd4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextHd4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextHd5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextHd5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextHd1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextHd1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextHd2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextHd2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextHd3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextHd3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextFt4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextFt4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextFt5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextFt5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextFt1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextFt1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextFt2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextFt2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextFt3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextFt3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnDialog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnDialog As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblMain4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMain4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnSaveTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveTemp As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnMSGSaveData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMSGSaveData As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''btnMSGCancelData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMSGCancelData As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblFreprjno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFreprjno As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFreprjno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFreprjno As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMassage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMassage1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chbFboiyn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chbFboiyn As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblFRePrjNm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFRePrjNm As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFRePrjNm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFRePrjNm As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblFrelocat1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFrelocat1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFrelocat1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFrelocat1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFrelocat2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFrelocat2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblFrelocat3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFrelocat3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''txtFrelocat3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFrelocat3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UpdatePanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel4 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblFreprovinc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFreprovinc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFreprovinc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFreprovinc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFrepostal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFrepostal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCodeMat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodeMat As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''txtCodeMat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodeMat As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblFlanddoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFlanddoc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tdFlandoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFlandoc As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFlandocUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFlandocUpload As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''hrefFlandoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hrefFlandoc As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblFredesc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFredesc1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFredesc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFredesc1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFredesc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFredesc2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFredesc3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFredesc3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblFtotarea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFtotarea As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFtotarea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFtotarea As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblFnoofland control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFnoofland As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFnoofland control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFnoofland As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblaFLADNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblaFLADNO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtaFLADNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtaFLADNO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblaFPCLANDNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblaFPCLANDNO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtaFPCLANDNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtaFPCLANDNO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSubChanod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubChanod As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''grdView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdView2 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnGridAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGridAdd As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''liTab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liTab1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liTab2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liTab2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDocument As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLandAllocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLandAllocation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate0 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate13 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tdFREQDOCAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOCAdd As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOCUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOCUpload As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''hrefFREQDOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hrefFREQDOC As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblConstructionPorject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConstructionPorject As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt11 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate14 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tdFCONSTRDOCAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFCONSTRDOCAdd As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFCONSTRDOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFCONSTRDOC As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFCONSTRDOCUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFCONSTRDOCUpload As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''hrefFCONSTRDOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hrefFCONSTRDOC As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblBuildingHomes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBuildingHomes As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt12 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate15 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tdFCONSTRDOC1Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFCONSTRDOC1Add As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFCONSTRDOC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFCONSTRDOC1 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFCONSTRDOC1Upload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFCONSTRDOC1Upload As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''hrefFCONSTRDOC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hrefFCONSTRDOC1 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblCityPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCityPlan As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt13 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate16 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tdFREQDOC1Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC1Add As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC1 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOC1Upload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC1Upload As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''hrefFREQDOC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hrefFREQDOC1 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblCommercialLand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommercialLand As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt14 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate17 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tdFREQDOC2Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC2Add As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC2 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOC2Upload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC2Upload As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''hrefFREQDOC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hrefFREQDOC2 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblGarbage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGarbage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt15 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate18 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tdFREQDOC3Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC3Add As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOC3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC3 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOC3Upload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC3Upload As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''hrefFREQDOC3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hrefFREQDOC3 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblContacts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContacts As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt16 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate19 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tdFREQDOC4Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC4Add As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOC4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC4 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOC4Upload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC4Upload As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''hrefFREQDOC4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hrefFREQDOC4 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblDrainage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDrainage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt17 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate20 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tdFREQDOC5Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC5Add As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOC5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC5 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOC5Upload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC5Upload As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''hrefFREQDOC5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hrefFREQDOC5 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblExpandElectricity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExpandElectricity As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt18 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate8 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate21 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tdFREQDOC6Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC6Add As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOC6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC6 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOC6Upload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC6Upload As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''hrefFREQDOC6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hrefFREQDOC6 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblPlumbingElectricity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlumbingElectricity As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt19 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate9 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate22 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tdFREQDOC7Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC7Add As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOC7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC7 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOC7Upload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC7Upload As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''hrefFREQDOC7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hrefFREQDOC7 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblScienceHill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScienceHill As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt20 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate10 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate23 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tdFREQDOC8Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC8Add As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOC8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC8 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOC8Upload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC8Upload As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''hrefFREQDOC8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hrefFREQDOC8 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblBillboards control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBillboards As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt21 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate11 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate24 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tdFREQDOC9Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC9Add As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOC9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC9 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOC9Upload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC9Upload As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''hrefFREQDOC9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hrefFREQDOC9 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblFilling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFilling As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt22 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate12 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate25 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tdFREQDOC10Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC10Add As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOC10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC10 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdFREQDOC10Upload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFREQDOC10Upload As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''hrefFREQDOC10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hrefFREQDOC10 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''ddlProjectType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProjectType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtProjectBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProjectBrand As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtProjectStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProjectStartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtProjectEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProjectEndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlConstructionStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlConstructionStatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtConstructionStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConstructionStartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMassage2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMassage2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtConstructionEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConstructionEndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMassage3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMassage3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlSaleStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSaleStatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtSaleStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSaleStartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMassage4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMassage4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSaleEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSaleEndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMassage5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMassage5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblHeaderDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeaderDelete As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBodydelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBodydelete As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnMSGDeleteData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMSGDeleteData As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnMSGCancelDataS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMSGCancelDataS As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEdit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnFileUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFileUpload As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDeleteFileUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteFileUpload As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''UpdatePanel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel5 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnReload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReload As Global.System.Web.UI.WebControls.Button
End Class
